<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:connectorconfiguration="http://wwww.bonitasoft.org/model/connector/configuration" xmlns:decision="http://www.bonitasoft.org/ns/studio/process/decision" xmlns:definition="http://www.bonitasoft.org/ns/connector/definition/6.1" xmlns:expression="http://www.bonitasoft.org/ns/studio/expression" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.3/notation" xmlns:parameter="http://www.bonitasoft.org/ns/studio/parameter" xmlns:process="http://www.bonitasoft.org/ns/studio/process" xsi:schemaLocation="http://www.bonitasoft.org/ns/studio/process/decision http://www.bonitasoft.org/ns/studio/process#//decision">
  <process:MainProcess xmi:id="_0ZmNEIU7Ee60zYC5i_hnmg" name="fww_bpm" bonitaModelVersion="7.12.0-004">
    <elements xmi:type="process:Pool" xmi:id="_0Zm0IIU7Ee60zYC5i_hnmg" name="passenger_flow">
      <elements xmi:type="process:Lane" xmi:id="_0Zm0IYU7Ee60zYC5i_hnmg" name="Application" actor="_cjh6YIU8Ee60zYC5i_hnmg">
        <elements xmi:type="process:StartEvent" xmi:id="_0Zm0IoU7Ee60zYC5i_hnmg" name="Start" outgoing="_0Zm0N4U7Ee60zYC5i_hnmg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_0Zm0I4U7Ee60zYC5i_hnmg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_0Zm0JIU7Ee60zYC5i_hnmg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_0Zm0JYU7Ee60zYC5i_hnmg" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_-yn2YIU7Ee60zYC5i_hnmg" name="Check Vaccine Status" outgoing="_OBGLsIU8Ee60zYC5i_hnmg" incoming="_vr3LQIU-Ee6tqtrNPEic8A">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_0Zm0J4U7Ee60zYC5i_hnmg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_0Zm0KIU7Ee60zYC5i_hnmg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_0Zm0KYU7Ee60zYC5i_hnmg" name="" content="" returnTypeFixed="true"/>
          <connectors xmi:type="process:Connector" xmi:id="_rVd8sIWUEe6BzrUxPUfMWg" name="Check Vaccine Status" definitionId="rest-get" event="ON_ENTER" definitionVersion="1.2.0">
            <configuration xmi:type="connectorconfiguration:ConnectorConfiguration" xmi:id="_rVd8sYWUEe6BzrUxPUfMWg" definitionId="rest-get" version="1.2.0" modelVersion="7.12.0-004">
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_rVd8soWUEe6BzrUxPUfMWg" key="url">
                <expression xmi:type="expression:Expression" xmi:id="_rVd8s4WUEe6BzrUxPUfMWg" name="url()" content="baseUrl_peduli_lindungi+'/peduli-lindungi/vaccine/status?nik='+passanger.id_number" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnTypeFixed="true">
                  <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_6pL-YIWUEe6BzrUxPUfMWg" name="passanger" dataType="_0Zm0U4U7Ee60zYC5i_hnmg" className="fww.model.Passanger"/>
                  <referencedElements xmi:type="parameter:Parameter" xmi:id="_6pMlcIWUEe6BzrUxPUfMWg" name="baseUrl_peduli_lindungi" typeClassname="java.lang.String"/>
                </expression>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_rVd8toWUEe6BzrUxPUfMWg" key="urlCookies">
                <expression xmi:type="expression:TableExpression" xmi:id="_rVd8t4WUEe6BzrUxPUfMWg"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_rVd8uIWUEe6BzrUxPUfMWg" key="urlHeaders">
                <expression xmi:type="expression:TableExpression" xmi:id="_rVd8uYWUEe6BzrUxPUfMWg"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_rVd8uoWUEe6BzrUxPUfMWg" key="do_not_follow_redirect">
                <expression xmi:type="expression:Expression" xmi:id="_rVd8u4WUEe6BzrUxPUfMWg" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_rVd8vIWUEe6BzrUxPUfMWg" key="ignore_body">
                <expression xmi:type="expression:Expression" xmi:id="_rVd8vYWUEe6BzrUxPUfMWg" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_rVd8voWUEe6BzrUxPUfMWg" key="TLS">
                <expression xmi:type="expression:Expression" xmi:id="_rVd8v4WUEe6BzrUxPUfMWg" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_rVd8wIWUEe6BzrUxPUfMWg" key="hostname_verifier">
                <expression xmi:type="expression:Expression" xmi:id="_rVd8wYWUEe6BzrUxPUfMWg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_rVd8woWUEe6BzrUxPUfMWg" key="trust_store_file">
                <expression xmi:type="expression:Expression" xmi:id="_rVd8w4WUEe6BzrUxPUfMWg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_rVd8xIWUEe6BzrUxPUfMWg" key="trust_store_password">
                <expression xmi:type="expression:Expression" xmi:id="_rVd8xYWUEe6BzrUxPUfMWg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_rVd8xoWUEe6BzrUxPUfMWg" key="key_store_file">
                <expression xmi:type="expression:Expression" xmi:id="_rVd8x4WUEe6BzrUxPUfMWg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_rVd8yIWUEe6BzrUxPUfMWg" key="key_store_password">
                <expression xmi:type="expression:Expression" xmi:id="_rVd8yYWUEe6BzrUxPUfMWg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_rVd8yoWUEe6BzrUxPUfMWg" key="auth_type">
                <expression xmi:type="expression:Expression" xmi:id="_rVd8y4WUEe6BzrUxPUfMWg" name="NONE" content="NONE" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_rVd8zIWUEe6BzrUxPUfMWg" key="auth_username">
                <expression xmi:type="expression:Expression" xmi:id="_rVd8zYWUEe6BzrUxPUfMWg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_rVd8zoWUEe6BzrUxPUfMWg" key="auth_password">
                <expression xmi:type="expression:Expression" xmi:id="_rVd8z4WUEe6BzrUxPUfMWg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_rVd80IWUEe6BzrUxPUfMWg" key="auth_host">
                <expression xmi:type="expression:Expression" xmi:id="_rVd80YWUEe6BzrUxPUfMWg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_rVd80oWUEe6BzrUxPUfMWg" key="auth_port">
                <expression xmi:type="expression:Expression" xmi:id="_rVd804WUEe6BzrUxPUfMWg" name="-1" content="-1" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_rVd81IWUEe6BzrUxPUfMWg" key="auth_realm">
                <expression xmi:type="expression:Expression" xmi:id="_rVd81YWUEe6BzrUxPUfMWg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_rVd81oWUEe6BzrUxPUfMWg" key="auth_preemptive">
                <expression xmi:type="expression:Expression" xmi:id="_rVd814WUEe6BzrUxPUfMWg" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_rVd82IWUEe6BzrUxPUfMWg" key="proxy_protocol">
                <expression xmi:type="expression:Expression" xmi:id="_rVd82YWUEe6BzrUxPUfMWg" name="HTTP" content="HTTP" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_rVd82oWUEe6BzrUxPUfMWg" key="proxy_host">
                <expression xmi:type="expression:Expression" xmi:id="_rVd824WUEe6BzrUxPUfMWg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_rVd83IWUEe6BzrUxPUfMWg" key="proxy_port">
                <expression xmi:type="expression:Expression" xmi:id="_rVd83YWUEe6BzrUxPUfMWg" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_rVd83oWUEe6BzrUxPUfMWg" key="proxy_username">
                <expression xmi:type="expression:Expression" xmi:id="_rVd834WUEe6BzrUxPUfMWg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_rVd84IWUEe6BzrUxPUfMWg" key="proxy_password">
                <expression xmi:type="expression:Expression" xmi:id="_rVd84YWUEe6BzrUxPUfMWg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_rVd84oWUEe6BzrUxPUfMWg" key="socket_timeout_ms">
                <expression xmi:type="expression:Expression" xmi:id="_rVd844WUEe6BzrUxPUfMWg" name="60000" content="60000" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_rVd85IWUEe6BzrUxPUfMWg" key="connection_timeout_ms">
                <expression xmi:type="expression:Expression" xmi:id="_rVd85YWUEe6BzrUxPUfMWg" name="60000" content="60000" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_rVd85oWUEe6BzrUxPUfMWg" key="trust_strategy">
                <expression xmi:type="expression:Expression" xmi:id="_rVd854WUEe6BzrUxPUfMWg" name="DEFAULT" content="DEFAULT" returnTypeFixed="true"/>
              </parameters>
            </configuration>
            <outputs xmi:type="expression:Operation" xmi:id="_rVd86IWUEe6BzrUxPUfMWg">
              <leftOperand xmi:type="expression:Expression" xmi:id="_rVd86YWUEe6BzrUxPUfMWg" name="passanger" content="passanger" type="TYPE_VARIABLE" returnType="fww.model.Passanger">
                <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_rVd86oWUEe6BzrUxPUfMWg" name="passanger" dataType="_0Zm0U4U7Ee60zYC5i_hnmg" className="fww.model.Passanger"/>
              </leftOperand>
              <rightOperand xmi:type="expression:Expression" xmi:id="_rVd864WUEe6BzrUxPUfMWg" name="newScript()" content="return bodyAsObject.data.vaccine_status" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
                <referencedElements xmi:type="definition:Output" xmi:id="_-DtuwIb4Ee6NpJx4hoX1Ww" name="bodyAsObject" type="java.lang.Object"/>
              </rightOperand>
              <operator xmi:type="expression:Operator" xmi:id="_rVd87YWUEe6BzrUxPUfMWg" type="JAVA_METHOD" expression="setVaccine_status">
                <inputTypes>java.lang.String</inputTypes>
              </operator>
            </outputs>
            <outputs xmi:type="expression:Operation" xmi:id="_rVd87oWUEe6BzrUxPUfMWg">
              <leftOperand xmi:type="expression:Expression" xmi:id="_rVd874WUEe6BzrUxPUfMWg"/>
              <rightOperand xmi:type="expression:Expression" xmi:id="_rVd88IWUEe6BzrUxPUfMWg" name="bodyAsObject" content="bodyAsObject" type="CONNECTOR_OUTPUT_TYPE" returnType="java.lang.Object">
                <referencedElements xmi:type="definition:Output" xmi:id="_rVd88YWUEe6BzrUxPUfMWg" name="bodyAsObject" type="java.lang.Object"/>
              </rightOperand>
              <operator xmi:type="expression:Operator" xmi:id="_rVd88oWUEe6BzrUxPUfMWg" type="ASSIGNMENT"/>
            </outputs>
            <outputs xmi:type="expression:Operation" xmi:id="_rVd884WUEe6BzrUxPUfMWg">
              <leftOperand xmi:type="expression:Expression" xmi:id="_rVd89IWUEe6BzrUxPUfMWg"/>
              <rightOperand xmi:type="expression:Expression" xmi:id="_rVd89YWUEe6BzrUxPUfMWg" name="headers" content="headers" type="CONNECTOR_OUTPUT_TYPE" returnType="java.util.Map">
                <referencedElements xmi:type="definition:Output" xmi:id="_rVd89oWUEe6BzrUxPUfMWg" name="headers" type="java.util.Map"/>
              </rightOperand>
              <operator xmi:type="expression:Operator" xmi:id="_rVd894WUEe6BzrUxPUfMWg" type="ASSIGNMENT"/>
            </outputs>
            <outputs xmi:type="expression:Operation" xmi:id="_rVd8-IWUEe6BzrUxPUfMWg">
              <leftOperand xmi:type="expression:Expression" xmi:id="_rVd8-YWUEe6BzrUxPUfMWg"/>
              <rightOperand xmi:type="expression:Expression" xmi:id="_rVd8-oWUEe6BzrUxPUfMWg" name="status_code" content="status_code" type="CONNECTOR_OUTPUT_TYPE" returnType="java.lang.Integer">
                <referencedElements xmi:type="definition:Output" xmi:id="_rVd8-4WUEe6BzrUxPUfMWg" name="status_code" type="java.lang.Integer"/>
              </rightOperand>
              <operator xmi:type="expression:Operator" xmi:id="_rVd8_IWUEe6BzrUxPUfMWg" type="ASSIGNMENT"/>
            </outputs>
            <outputs xmi:type="expression:Operation" xmi:id="_rVd8_YWUEe6BzrUxPUfMWg">
              <leftOperand xmi:type="expression:Expression" xmi:id="_rVd8_oWUEe6BzrUxPUfMWg"/>
              <rightOperand xmi:type="expression:Expression" xmi:id="_rVd8_4WUEe6BzrUxPUfMWg" name="status_message" content="status_message" type="CONNECTOR_OUTPUT_TYPE">
                <referencedElements xmi:type="definition:Output" xmi:id="_rVd9AIWUEe6BzrUxPUfMWg" name="status_message" type="java.lang.String"/>
              </rightOperand>
              <operator xmi:type="expression:Operator" xmi:id="_rVd9AYWUEe6BzrUxPUfMWg" type="ASSIGNMENT"/>
            </outputs>
          </connectors>
          <loopCondition xmi:type="expression:Expression" xmi:id="_0Zm0KoU7Ee60zYC5i_hnmg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_0Zm0K4U7Ee60zYC5i_hnmg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_0Zm0LIU7Ee60zYC5i_hnmg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_0Zm0LYU7Ee60zYC5i_hnmg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_0Zm0LoU7Ee60zYC5i_hnmg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_KHuGYIU8Ee60zYC5i_hnmg" name="Update Passenger Vaccine" outgoing="_4NvgEIbbEe6NpJx4hoX1Ww" incoming="_OBGLsIU8Ee60zYC5i_hnmg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_KHuGYoU8Ee60zYC5i_hnmg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_KHuGYYU8Ee60zYC5i_hnmg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_KHuGY4U8Ee60zYC5i_hnmg" name="" content="" returnTypeFixed="true"/>
          <connectors xmi:type="process:Connector" xmi:id="_oJOGUIWYEe6BzrUxPUfMWg" name="Update Passenger" definitionId="rest-put" event="ON_ENTER" definitionVersion="1.3.0">
            <configuration xmi:type="connectorconfiguration:ConnectorConfiguration" xmi:id="_oJOGUYWYEe6BzrUxPUfMWg" definitionId="rest-put" version="1.3.0" modelVersion="7.12.0-004">
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_oJOGUoWYEe6BzrUxPUfMWg" key="url">
                <expression xmi:type="expression:Expression" xmi:id="_oJOGU4WYEe6BzrUxPUfMWg" name="url()" content="baseUrl_wrapper+'/api/private/v1/passenger'" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnTypeFixed="true">
                  <referencedElements xmi:type="parameter:Parameter" xmi:id="_oJOGVIWYEe6BzrUxPUfMWg" name="baseUrl_wrapper" typeClassname="java.lang.String"/>
                </expression>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_oJOGVYWYEe6BzrUxPUfMWg" key="contentType">
                <expression xmi:type="expression:Expression" xmi:id="_oJOGVoWYEe6BzrUxPUfMWg" name="application/json" content="application/json" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_oJOGV4WYEe6BzrUxPUfMWg" key="charset">
                <expression xmi:type="expression:Expression" xmi:id="_oJOGWIWYEe6BzrUxPUfMWg" name="UTF-8" content="UTF-8" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_oJOGWYWYEe6BzrUxPUfMWg" key="urlCookies">
                <expression xmi:type="expression:TableExpression" xmi:id="_oJOGWoWYEe6BzrUxPUfMWg"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_oJOGW4WYEe6BzrUxPUfMWg" key="urlHeaders">
                <expression xmi:type="expression:TableExpression" xmi:id="_oJOGXIWYEe6BzrUxPUfMWg"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_oJOGXYWYEe6BzrUxPUfMWg" key="body">
                <expression xmi:type="expression:Expression" xmi:id="_oJOGXoWYEe6BzrUxPUfMWg" name="&lt;pattern-expression>" content="{&#xA;&#x9;&quot;id_number&quot;: &quot;${passanger.id_number}&quot;,&#xA;&#x9;&quot;vaccine_status&quot;: &quot;${passanger.vaccine_status}&quot;,&#xA;&#x9;&quot;is_verified_dukcapil&quot;: ${passanger.is_verified_dukcapil},&#xA;&#x9;&quot;case_id&quot;: ${processInstanceId}&#xA;}" type="TYPE_PATTERN" returnTypeFixed="true">
                  <referencedElements xmi:type="expression:Expression" xmi:id="_wdKqcIcBEe6NpJx4hoX1Ww" name="passanger.id_number" content="passanger.id_number" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
                    <referencedElements xmi:type="expression:Expression" xmi:id="_wdKqcYcBEe6NpJx4hoX1Ww" name="passanger" content="passanger" type="TYPE_VARIABLE" returnType="fww.model.Passanger">
                      <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_wdKqcocBEe6NpJx4hoX1Ww" name="passanger" dataType="_0Zm0U4U7Ee60zYC5i_hnmg" className="fww.model.Passanger"/>
                    </referencedElements>
                  </referencedElements>
                  <referencedElements xmi:type="expression:Expression" xmi:id="_wdKqc4cBEe6NpJx4hoX1Ww" name="passanger.vaccine_status" content="passanger.vaccine_status" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
                    <referencedElements xmi:type="expression:Expression" xmi:id="_wdKqdIcBEe6NpJx4hoX1Ww" name="passanger" content="passanger" type="TYPE_VARIABLE" returnType="fww.model.Passanger">
                      <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_wdKqdYcBEe6NpJx4hoX1Ww" name="passanger" dataType="_0Zm0U4U7Ee60zYC5i_hnmg" className="fww.model.Passanger"/>
                    </referencedElements>
                  </referencedElements>
                  <referencedElements xmi:type="expression:Expression" xmi:id="_wdKqdocBEe6NpJx4hoX1Ww" name="passanger.is_verified_dukcapil" content="passanger.is_verified_dukcapil" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
                    <referencedElements xmi:type="expression:Expression" xmi:id="_wdKqd4cBEe6NpJx4hoX1Ww" name="passanger" content="passanger" type="TYPE_VARIABLE" returnType="fww.model.Passanger">
                      <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_wdKqeIcBEe6NpJx4hoX1Ww" name="passanger" dataType="_0Zm0U4U7Ee60zYC5i_hnmg" className="fww.model.Passanger"/>
                    </referencedElements>
                  </referencedElements>
                  <referencedElements xmi:type="expression:Expression" xmi:id="_wdKqeYcBEe6NpJx4hoX1Ww" name="processInstanceId" content="processInstanceId" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
                    <referencedElements xmi:type="expression:Expression" xmi:id="_wdKqeocBEe6NpJx4hoX1Ww" name="processInstanceId" content="processInstanceId" type="TYPE_ENGINE_CONSTANT" returnType="java.lang.Long" returnTypeFixed="true"/>
                  </referencedElements>
                </expression>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_oJOGaoWYEe6BzrUxPUfMWg" key="do_not_follow_redirect">
                <expression xmi:type="expression:Expression" xmi:id="_oJOGa4WYEe6BzrUxPUfMWg" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_oJOGbIWYEe6BzrUxPUfMWg" key="ignore_body">
                <expression xmi:type="expression:Expression" xmi:id="_oJOGbYWYEe6BzrUxPUfMWg" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_oJOGboWYEe6BzrUxPUfMWg" key="TLS">
                <expression xmi:type="expression:Expression" xmi:id="_oJOGb4WYEe6BzrUxPUfMWg" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_oJOGcIWYEe6BzrUxPUfMWg" key="hostname_verifier">
                <expression xmi:type="expression:Expression" xmi:id="_oJOGcYWYEe6BzrUxPUfMWg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_oJOGcoWYEe6BzrUxPUfMWg" key="trust_store_file">
                <expression xmi:type="expression:Expression" xmi:id="_oJOGc4WYEe6BzrUxPUfMWg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_oJOGdIWYEe6BzrUxPUfMWg" key="trust_store_password">
                <expression xmi:type="expression:Expression" xmi:id="_oJOGdYWYEe6BzrUxPUfMWg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_oJOGdoWYEe6BzrUxPUfMWg" key="key_store_file">
                <expression xmi:type="expression:Expression" xmi:id="_oJOGd4WYEe6BzrUxPUfMWg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_oJOGeIWYEe6BzrUxPUfMWg" key="key_store_password">
                <expression xmi:type="expression:Expression" xmi:id="_oJOGeYWYEe6BzrUxPUfMWg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_oJOGeoWYEe6BzrUxPUfMWg" key="auth_type">
                <expression xmi:type="expression:Expression" xmi:id="_oJOGe4WYEe6BzrUxPUfMWg" name="NONE" content="NONE" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_oJOGfIWYEe6BzrUxPUfMWg" key="auth_username">
                <expression xmi:type="expression:Expression" xmi:id="_oJOGfYWYEe6BzrUxPUfMWg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_oJOGfoWYEe6BzrUxPUfMWg" key="auth_password">
                <expression xmi:type="expression:Expression" xmi:id="_oJOGf4WYEe6BzrUxPUfMWg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_oJOGgIWYEe6BzrUxPUfMWg" key="auth_host">
                <expression xmi:type="expression:Expression" xmi:id="_oJOGgYWYEe6BzrUxPUfMWg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_oJOGgoWYEe6BzrUxPUfMWg" key="auth_port">
                <expression xmi:type="expression:Expression" xmi:id="_oJOGg4WYEe6BzrUxPUfMWg" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_oJOGhIWYEe6BzrUxPUfMWg" key="auth_realm">
                <expression xmi:type="expression:Expression" xmi:id="_oJOGhYWYEe6BzrUxPUfMWg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_oJOGhoWYEe6BzrUxPUfMWg" key="auth_preemptive">
                <expression xmi:type="expression:Expression" xmi:id="_oJOGh4WYEe6BzrUxPUfMWg" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_oJOGiIWYEe6BzrUxPUfMWg" key="proxy_protocol">
                <expression xmi:type="expression:Expression" xmi:id="_oJOGiYWYEe6BzrUxPUfMWg" name="HTTP" content="HTTP" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_oJOGioWYEe6BzrUxPUfMWg" key="proxy_host">
                <expression xmi:type="expression:Expression" xmi:id="_oJOGi4WYEe6BzrUxPUfMWg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_oJOGjIWYEe6BzrUxPUfMWg" key="proxy_port">
                <expression xmi:type="expression:Expression" xmi:id="_oJOGjYWYEe6BzrUxPUfMWg" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_oJOGjoWYEe6BzrUxPUfMWg" key="proxy_username">
                <expression xmi:type="expression:Expression" xmi:id="_oJOGj4WYEe6BzrUxPUfMWg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_oJOGkIWYEe6BzrUxPUfMWg" key="proxy_password">
                <expression xmi:type="expression:Expression" xmi:id="_oJOGkYWYEe6BzrUxPUfMWg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_oJOGkoWYEe6BzrUxPUfMWg" key="socket_timeout_ms">
                <expression xmi:type="expression:Expression" xmi:id="_oJOGk4WYEe6BzrUxPUfMWg" name="60000" content="60000" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_oJOGlIWYEe6BzrUxPUfMWg" key="connection_timeout_ms">
                <expression xmi:type="expression:Expression" xmi:id="_oJOGlYWYEe6BzrUxPUfMWg" name="60000" content="60000" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_oJOGloWYEe6BzrUxPUfMWg" key="trust_strategy">
                <expression xmi:type="expression:Expression" xmi:id="_oJOGl4WYEe6BzrUxPUfMWg" name="DEFAULT" content="DEFAULT" returnTypeFixed="true"/>
              </parameters>
            </configuration>
            <outputs xmi:type="expression:Operation" xmi:id="_oJOGmIWYEe6BzrUxPUfMWg">
              <leftOperand xmi:type="expression:Expression" xmi:id="_oJOGmYWYEe6BzrUxPUfMWg"/>
              <rightOperand xmi:type="expression:Expression" xmi:id="_oJOGmoWYEe6BzrUxPUfMWg" name="bodyAsString" content="bodyAsString" type="CONNECTOR_OUTPUT_TYPE">
                <referencedElements xmi:type="definition:Output" xmi:id="_oJOGm4WYEe6BzrUxPUfMWg" name="bodyAsString" type="java.lang.String"/>
              </rightOperand>
              <operator xmi:type="expression:Operator" xmi:id="_oJOGnIWYEe6BzrUxPUfMWg" type="ASSIGNMENT"/>
            </outputs>
            <outputs xmi:type="expression:Operation" xmi:id="_oJOGnYWYEe6BzrUxPUfMWg">
              <leftOperand xmi:type="expression:Expression" xmi:id="_oJOGnoWYEe6BzrUxPUfMWg"/>
              <rightOperand xmi:type="expression:Expression" xmi:id="_oJOGn4WYEe6BzrUxPUfMWg" name="bodyAsObject" content="bodyAsObject" type="CONNECTOR_OUTPUT_TYPE" returnType="java.lang.Object">
                <referencedElements xmi:type="definition:Output" xmi:id="_oJOGoIWYEe6BzrUxPUfMWg" name="bodyAsObject" type="java.lang.Object"/>
              </rightOperand>
              <operator xmi:type="expression:Operator" xmi:id="_oJOGoYWYEe6BzrUxPUfMWg" type="ASSIGNMENT"/>
            </outputs>
            <outputs xmi:type="expression:Operation" xmi:id="_oJOGooWYEe6BzrUxPUfMWg">
              <leftOperand xmi:type="expression:Expression" xmi:id="_oJOGo4WYEe6BzrUxPUfMWg"/>
              <rightOperand xmi:type="expression:Expression" xmi:id="_oJOGpIWYEe6BzrUxPUfMWg" name="headers" content="headers" type="CONNECTOR_OUTPUT_TYPE" returnType="java.util.Map">
                <referencedElements xmi:type="definition:Output" xmi:id="_oJOGpYWYEe6BzrUxPUfMWg" name="headers" type="java.util.Map"/>
              </rightOperand>
              <operator xmi:type="expression:Operator" xmi:id="_oJOGpoWYEe6BzrUxPUfMWg" type="ASSIGNMENT"/>
            </outputs>
            <outputs xmi:type="expression:Operation" xmi:id="_oJOGp4WYEe6BzrUxPUfMWg">
              <leftOperand xmi:type="expression:Expression" xmi:id="_oJOGqIWYEe6BzrUxPUfMWg"/>
              <rightOperand xmi:type="expression:Expression" xmi:id="_oJOGqYWYEe6BzrUxPUfMWg" name="status_code" content="status_code" type="CONNECTOR_OUTPUT_TYPE" returnType="java.lang.Integer">
                <referencedElements xmi:type="definition:Output" xmi:id="_oJOGqoWYEe6BzrUxPUfMWg" name="status_code" type="java.lang.Integer"/>
              </rightOperand>
              <operator xmi:type="expression:Operator" xmi:id="_oJOGq4WYEe6BzrUxPUfMWg" type="ASSIGNMENT"/>
            </outputs>
            <outputs xmi:type="expression:Operation" xmi:id="_oJOGrIWYEe6BzrUxPUfMWg">
              <leftOperand xmi:type="expression:Expression" xmi:id="_oJOGrYWYEe6BzrUxPUfMWg"/>
              <rightOperand xmi:type="expression:Expression" xmi:id="_oJOGroWYEe6BzrUxPUfMWg" name="status_message" content="status_message" type="CONNECTOR_OUTPUT_TYPE">
                <referencedElements xmi:type="definition:Output" xmi:id="_oJOGr4WYEe6BzrUxPUfMWg" name="status_message" type="java.lang.String"/>
              </rightOperand>
              <operator xmi:type="expression:Operator" xmi:id="_oJOGsIWYEe6BzrUxPUfMWg" type="ASSIGNMENT"/>
            </outputs>
          </connectors>
          <connectors xmi:type="process:Connector" xmi:id="_mxy10IWXEe6BzrUxPUfMWg" name="Save Workflow" definitionId="rest-post" event="ON_ENTER" definitionVersion="1.3.0">
            <configuration xmi:type="connectorconfiguration:ConnectorConfiguration" xmi:id="_mxy10YWXEe6BzrUxPUfMWg" definitionId="rest-post" version="1.3.0" modelVersion="7.12.0-004">
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_mxy10oWXEe6BzrUxPUfMWg" key="url">
                <expression xmi:type="expression:Expression" xmi:id="_mxy104WXEe6BzrUxPUfMWg" name="url()" content="baseUrl_wrapper+'/api/private/v1/workflow'" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnTypeFixed="true">
                  <referencedElements xmi:type="parameter:Parameter" xmi:id="_mxy11IWXEe6BzrUxPUfMWg" name="baseUrl_wrapper" typeClassname="java.lang.String"/>
                </expression>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_mxy11YWXEe6BzrUxPUfMWg" key="contentType">
                <expression xmi:type="expression:Expression" xmi:id="_mxy11oWXEe6BzrUxPUfMWg" name="application/json" content="application/json" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_mxy114WXEe6BzrUxPUfMWg" key="charset">
                <expression xmi:type="expression:Expression" xmi:id="_mxy12IWXEe6BzrUxPUfMWg" name="UTF-8" content="UTF-8" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_mxy12YWXEe6BzrUxPUfMWg" key="urlCookies">
                <expression xmi:type="expression:TableExpression" xmi:id="_mxy12oWXEe6BzrUxPUfMWg"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_mxy124WXEe6BzrUxPUfMWg" key="urlHeaders">
                <expression xmi:type="expression:TableExpression" xmi:id="_mxy13IWXEe6BzrUxPUfMWg"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_mxy13YWXEe6BzrUxPUfMWg" key="body">
                <expression xmi:type="expression:Expression" xmi:id="_mxy13oWXEe6BzrUxPUfMWg" name="&lt;pattern-expression>" content="{&#xA;&#x9;&quot;case_id&quot;: ${processInstanceId},&#xA;&#x9;&quot;task_name&quot;: &quot;Update Passenger Vaccine&quot;,&#xA;&#x9;&quot;process_name&quot;: &quot;passenger_flow&quot;&#xA;}" type="TYPE_PATTERN" returnTypeFixed="true">
                  <referencedElements xmi:type="expression:Expression" xmi:id="_0O_WQIcBEe6NpJx4hoX1Ww" name="processInstanceId" content="processInstanceId" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
                    <referencedElements xmi:type="expression:Expression" xmi:id="_0O_WQYcBEe6NpJx4hoX1Ww" name="processInstanceId" content="processInstanceId" type="TYPE_ENGINE_CONSTANT" returnType="java.lang.Long" returnTypeFixed="true"/>
                  </referencedElements>
                </expression>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_mxy14YWXEe6BzrUxPUfMWg" key="do_not_follow_redirect">
                <expression xmi:type="expression:Expression" xmi:id="_mxy14oWXEe6BzrUxPUfMWg" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_mxy144WXEe6BzrUxPUfMWg" key="ignore_body">
                <expression xmi:type="expression:Expression" xmi:id="_mxy15IWXEe6BzrUxPUfMWg" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_mxy15YWXEe6BzrUxPUfMWg" key="TLS">
                <expression xmi:type="expression:Expression" xmi:id="_mxy15oWXEe6BzrUxPUfMWg" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_mxy154WXEe6BzrUxPUfMWg" key="hostname_verifier">
                <expression xmi:type="expression:Expression" xmi:id="_mxy16IWXEe6BzrUxPUfMWg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_mxy16YWXEe6BzrUxPUfMWg" key="trust_store_file">
                <expression xmi:type="expression:Expression" xmi:id="_mxy16oWXEe6BzrUxPUfMWg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_mxy164WXEe6BzrUxPUfMWg" key="trust_store_password">
                <expression xmi:type="expression:Expression" xmi:id="_mxy17IWXEe6BzrUxPUfMWg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_mxy17YWXEe6BzrUxPUfMWg" key="key_store_file">
                <expression xmi:type="expression:Expression" xmi:id="_mxy17oWXEe6BzrUxPUfMWg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_mxy174WXEe6BzrUxPUfMWg" key="key_store_password">
                <expression xmi:type="expression:Expression" xmi:id="_mxy18IWXEe6BzrUxPUfMWg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_mxy18YWXEe6BzrUxPUfMWg" key="auth_type">
                <expression xmi:type="expression:Expression" xmi:id="_mxy18oWXEe6BzrUxPUfMWg" name="NONE" content="NONE" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_mxy184WXEe6BzrUxPUfMWg" key="auth_username">
                <expression xmi:type="expression:Expression" xmi:id="_mxy19IWXEe6BzrUxPUfMWg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_mxy19YWXEe6BzrUxPUfMWg" key="auth_password">
                <expression xmi:type="expression:Expression" xmi:id="_mxy19oWXEe6BzrUxPUfMWg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_mxy194WXEe6BzrUxPUfMWg" key="auth_host">
                <expression xmi:type="expression:Expression" xmi:id="_mxy1-IWXEe6BzrUxPUfMWg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_mxy1-YWXEe6BzrUxPUfMWg" key="auth_port">
                <expression xmi:type="expression:Expression" xmi:id="_mxy1-oWXEe6BzrUxPUfMWg" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_mxy1-4WXEe6BzrUxPUfMWg" key="auth_realm">
                <expression xmi:type="expression:Expression" xmi:id="_mxy1_IWXEe6BzrUxPUfMWg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_mxy1_YWXEe6BzrUxPUfMWg" key="auth_preemptive">
                <expression xmi:type="expression:Expression" xmi:id="_mxy1_oWXEe6BzrUxPUfMWg" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_mxy1_4WXEe6BzrUxPUfMWg" key="proxy_protocol">
                <expression xmi:type="expression:Expression" xmi:id="_mxy2AIWXEe6BzrUxPUfMWg" name="HTTP" content="HTTP" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_mxy2AYWXEe6BzrUxPUfMWg" key="proxy_host">
                <expression xmi:type="expression:Expression" xmi:id="_mxy2AoWXEe6BzrUxPUfMWg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_mxy2A4WXEe6BzrUxPUfMWg" key="proxy_port">
                <expression xmi:type="expression:Expression" xmi:id="_mxy2BIWXEe6BzrUxPUfMWg" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_mxy2BYWXEe6BzrUxPUfMWg" key="proxy_username">
                <expression xmi:type="expression:Expression" xmi:id="_mxy2BoWXEe6BzrUxPUfMWg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_mxy2B4WXEe6BzrUxPUfMWg" key="proxy_password">
                <expression xmi:type="expression:Expression" xmi:id="_mxy2CIWXEe6BzrUxPUfMWg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_mxy2CYWXEe6BzrUxPUfMWg" key="socket_timeout_ms">
                <expression xmi:type="expression:Expression" xmi:id="_mxy2CoWXEe6BzrUxPUfMWg" name="60000" content="60000" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_mxy2C4WXEe6BzrUxPUfMWg" key="connection_timeout_ms">
                <expression xmi:type="expression:Expression" xmi:id="_mxy2DIWXEe6BzrUxPUfMWg" name="60000" content="60000" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_mxy2DYWXEe6BzrUxPUfMWg" key="trust_strategy">
                <expression xmi:type="expression:Expression" xmi:id="_mxy2DoWXEe6BzrUxPUfMWg" name="DEFAULT" content="DEFAULT" returnTypeFixed="true"/>
              </parameters>
            </configuration>
            <outputs xmi:type="expression:Operation" xmi:id="_mxy2D4WXEe6BzrUxPUfMWg">
              <leftOperand xmi:type="expression:Expression" xmi:id="_mxy2EIWXEe6BzrUxPUfMWg"/>
              <rightOperand xmi:type="expression:Expression" xmi:id="_mxy2EYWXEe6BzrUxPUfMWg" name="bodyAsString" content="bodyAsString" type="CONNECTOR_OUTPUT_TYPE">
                <referencedElements xmi:type="definition:Output" xmi:id="_mxy2EoWXEe6BzrUxPUfMWg" name="bodyAsString" type="java.lang.String"/>
              </rightOperand>
              <operator xmi:type="expression:Operator" xmi:id="_mxy2E4WXEe6BzrUxPUfMWg" type="ASSIGNMENT"/>
            </outputs>
            <outputs xmi:type="expression:Operation" xmi:id="_mxy2FIWXEe6BzrUxPUfMWg">
              <leftOperand xmi:type="expression:Expression" xmi:id="_mxy2FYWXEe6BzrUxPUfMWg"/>
              <rightOperand xmi:type="expression:Expression" xmi:id="_mxy2FoWXEe6BzrUxPUfMWg" name="bodyAsObject" content="bodyAsObject" type="CONNECTOR_OUTPUT_TYPE" returnType="java.lang.Object">
                <referencedElements xmi:type="definition:Output" xmi:id="_mxy2F4WXEe6BzrUxPUfMWg" name="bodyAsObject" type="java.lang.Object"/>
              </rightOperand>
              <operator xmi:type="expression:Operator" xmi:id="_mxy2GIWXEe6BzrUxPUfMWg" type="ASSIGNMENT"/>
            </outputs>
            <outputs xmi:type="expression:Operation" xmi:id="_mxy2GYWXEe6BzrUxPUfMWg">
              <leftOperand xmi:type="expression:Expression" xmi:id="_mxy2GoWXEe6BzrUxPUfMWg"/>
              <rightOperand xmi:type="expression:Expression" xmi:id="_mxy2G4WXEe6BzrUxPUfMWg" name="headers" content="headers" type="CONNECTOR_OUTPUT_TYPE" returnType="java.util.Map">
                <referencedElements xmi:type="definition:Output" xmi:id="_mxy2HIWXEe6BzrUxPUfMWg" name="headers" type="java.util.Map"/>
              </rightOperand>
              <operator xmi:type="expression:Operator" xmi:id="_mxy2HYWXEe6BzrUxPUfMWg" type="ASSIGNMENT"/>
            </outputs>
            <outputs xmi:type="expression:Operation" xmi:id="_mxy2HoWXEe6BzrUxPUfMWg">
              <leftOperand xmi:type="expression:Expression" xmi:id="_mxy2H4WXEe6BzrUxPUfMWg"/>
              <rightOperand xmi:type="expression:Expression" xmi:id="_mxy2IIWXEe6BzrUxPUfMWg" name="status_code" content="status_code" type="CONNECTOR_OUTPUT_TYPE" returnType="java.lang.Integer">
                <referencedElements xmi:type="definition:Output" xmi:id="_mxy2IYWXEe6BzrUxPUfMWg" name="status_code" type="java.lang.Integer"/>
              </rightOperand>
              <operator xmi:type="expression:Operator" xmi:id="_mxy2IoWXEe6BzrUxPUfMWg" type="ASSIGNMENT"/>
            </outputs>
            <outputs xmi:type="expression:Operation" xmi:id="_mxy2I4WXEe6BzrUxPUfMWg">
              <leftOperand xmi:type="expression:Expression" xmi:id="_mxy2JIWXEe6BzrUxPUfMWg"/>
              <rightOperand xmi:type="expression:Expression" xmi:id="_mxy2JYWXEe6BzrUxPUfMWg" name="status_message" content="status_message" type="CONNECTOR_OUTPUT_TYPE">
                <referencedElements xmi:type="definition:Output" xmi:id="_mxy2JoWXEe6BzrUxPUfMWg" name="status_message" type="java.lang.String"/>
              </rightOperand>
              <operator xmi:type="expression:Operator" xmi:id="_mxy2J4WXEe6BzrUxPUfMWg" type="ASSIGNMENT"/>
            </outputs>
          </connectors>
          <loopCondition xmi:type="expression:Expression" xmi:id="_KHuGZIU8Ee60zYC5i_hnmg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_KHuGZYU8Ee60zYC5i_hnmg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_KHuGZoU8Ee60zYC5i_hnmg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_KHuGaIU8Ee60zYC5i_hnmg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_KHuGZ4U8Ee60zYC5i_hnmg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndTerminatedEvent" xmi:id="_PouQ0IU8Ee60zYC5i_hnmg" name="close" incoming="_4o05kIbbEe6NpJx4hoX1Ww">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_Pou34IU8Ee60zYC5i_hnmg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_PouQ0YU8Ee60zYC5i_hnmg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_Pou34YU8Ee60zYC5i_hnmg" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_UJtd0IU-Ee6tqtrNPEic8A" name="Validate Dukcapil ID" outgoing="_tkeA8IU-Ee6tqtrNPEic8A" incoming="_0Zm0N4U7Ee60zYC5i_hnmg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_UJtd0YU-Ee6tqtrNPEic8A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_UJtd0oU-Ee6tqtrNPEic8A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_UJtd04U-Ee6tqtrNPEic8A" name="" content="" returnTypeFixed="true"/>
          <connectors xmi:type="process:Connector" xmi:id="_i0Wv4IWXEe6BzrUxPUfMWg" name="Save Workflow" definitionId="rest-post" event="ON_ENTER" definitionVersion="1.3.0">
            <configuration xmi:type="connectorconfiguration:ConnectorConfiguration" xmi:id="_i0Wv4YWXEe6BzrUxPUfMWg" definitionId="rest-post" version="1.3.0" modelVersion="7.12.0-004">
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_i0Wv4oWXEe6BzrUxPUfMWg" key="url">
                <expression xmi:type="expression:Expression" xmi:id="_i0Wv44WXEe6BzrUxPUfMWg" name="url()" content="baseUrl_wrapper+'/api/private/v1/workflow'" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnTypeFixed="true">
                  <referencedElements xmi:type="parameter:Parameter" xmi:id="_i0Wv5IWXEe6BzrUxPUfMWg" name="baseUrl_wrapper" typeClassname="java.lang.String"/>
                </expression>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_i0Wv5YWXEe6BzrUxPUfMWg" key="contentType">
                <expression xmi:type="expression:Expression" xmi:id="_i0Wv5oWXEe6BzrUxPUfMWg" name="application/json" content="application/json" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_i0Wv54WXEe6BzrUxPUfMWg" key="charset">
                <expression xmi:type="expression:Expression" xmi:id="_i0Wv6IWXEe6BzrUxPUfMWg" name="UTF-8" content="UTF-8" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_i0Wv6YWXEe6BzrUxPUfMWg" key="urlCookies">
                <expression xmi:type="expression:TableExpression" xmi:id="_i0Wv6oWXEe6BzrUxPUfMWg"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_i0Wv64WXEe6BzrUxPUfMWg" key="urlHeaders">
                <expression xmi:type="expression:TableExpression" xmi:id="_i0Wv7IWXEe6BzrUxPUfMWg"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_i0Wv7YWXEe6BzrUxPUfMWg" key="body">
                <expression xmi:type="expression:Expression" xmi:id="_i0Wv7oWXEe6BzrUxPUfMWg" name="&lt;pattern-expression>" content="{&#xA;&#x9;&quot;case_id&quot;: ${processInstanceId},&#xA;&#x9;&quot;task_name&quot;: &quot;Validate Dukcapil ID&quot;,&#xA;&#x9;&quot;process_name&quot;: &quot;passenger_flow&quot;&#xA;}" type="TYPE_PATTERN" returnTypeFixed="true">
                  <referencedElements xmi:type="expression:Expression" xmi:id="_i0Wv74WXEe6BzrUxPUfMWg" name="processInstanceId" content="processInstanceId" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
                    <referencedElements xmi:type="expression:Expression" xmi:id="_i0Wv8IWXEe6BzrUxPUfMWg" name="processInstanceId" content="processInstanceId" type="TYPE_ENGINE_CONSTANT" returnType="java.lang.Long" returnTypeFixed="true"/>
                  </referencedElements>
                </expression>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_i0Wv8YWXEe6BzrUxPUfMWg" key="do_not_follow_redirect">
                <expression xmi:type="expression:Expression" xmi:id="_i0Wv8oWXEe6BzrUxPUfMWg" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_i0Wv84WXEe6BzrUxPUfMWg" key="ignore_body">
                <expression xmi:type="expression:Expression" xmi:id="_i0Wv9IWXEe6BzrUxPUfMWg" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_i0Wv9YWXEe6BzrUxPUfMWg" key="TLS">
                <expression xmi:type="expression:Expression" xmi:id="_i0Wv9oWXEe6BzrUxPUfMWg" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_i0Wv94WXEe6BzrUxPUfMWg" key="hostname_verifier">
                <expression xmi:type="expression:Expression" xmi:id="_i0Wv-IWXEe6BzrUxPUfMWg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_i0Wv-YWXEe6BzrUxPUfMWg" key="trust_store_file">
                <expression xmi:type="expression:Expression" xmi:id="_i0Wv-oWXEe6BzrUxPUfMWg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_i0Wv-4WXEe6BzrUxPUfMWg" key="trust_store_password">
                <expression xmi:type="expression:Expression" xmi:id="_i0Wv_IWXEe6BzrUxPUfMWg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_i0Wv_YWXEe6BzrUxPUfMWg" key="key_store_file">
                <expression xmi:type="expression:Expression" xmi:id="_i0Wv_oWXEe6BzrUxPUfMWg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_i0Wv_4WXEe6BzrUxPUfMWg" key="key_store_password">
                <expression xmi:type="expression:Expression" xmi:id="_i0WwAIWXEe6BzrUxPUfMWg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_i0WwAYWXEe6BzrUxPUfMWg" key="auth_type">
                <expression xmi:type="expression:Expression" xmi:id="_i0WwAoWXEe6BzrUxPUfMWg" name="NONE" content="NONE" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_i0WwA4WXEe6BzrUxPUfMWg" key="auth_username">
                <expression xmi:type="expression:Expression" xmi:id="_i0WwBIWXEe6BzrUxPUfMWg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_i0WwBYWXEe6BzrUxPUfMWg" key="auth_password">
                <expression xmi:type="expression:Expression" xmi:id="_i0WwBoWXEe6BzrUxPUfMWg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_i0WwB4WXEe6BzrUxPUfMWg" key="auth_host">
                <expression xmi:type="expression:Expression" xmi:id="_i0WwCIWXEe6BzrUxPUfMWg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_i0WwCYWXEe6BzrUxPUfMWg" key="auth_port">
                <expression xmi:type="expression:Expression" xmi:id="_i0WwCoWXEe6BzrUxPUfMWg" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_i0WwC4WXEe6BzrUxPUfMWg" key="auth_realm">
                <expression xmi:type="expression:Expression" xmi:id="_i0WwDIWXEe6BzrUxPUfMWg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_i0WwDYWXEe6BzrUxPUfMWg" key="auth_preemptive">
                <expression xmi:type="expression:Expression" xmi:id="_i0WwDoWXEe6BzrUxPUfMWg" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_i0WwD4WXEe6BzrUxPUfMWg" key="proxy_protocol">
                <expression xmi:type="expression:Expression" xmi:id="_i0WwEIWXEe6BzrUxPUfMWg" name="HTTP" content="HTTP" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_i0WwEYWXEe6BzrUxPUfMWg" key="proxy_host">
                <expression xmi:type="expression:Expression" xmi:id="_i0WwEoWXEe6BzrUxPUfMWg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_i0WwE4WXEe6BzrUxPUfMWg" key="proxy_port">
                <expression xmi:type="expression:Expression" xmi:id="_i0WwFIWXEe6BzrUxPUfMWg" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_i0WwFYWXEe6BzrUxPUfMWg" key="proxy_username">
                <expression xmi:type="expression:Expression" xmi:id="_i0WwFoWXEe6BzrUxPUfMWg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_i0WwF4WXEe6BzrUxPUfMWg" key="proxy_password">
                <expression xmi:type="expression:Expression" xmi:id="_i0WwGIWXEe6BzrUxPUfMWg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_i0WwGYWXEe6BzrUxPUfMWg" key="socket_timeout_ms">
                <expression xmi:type="expression:Expression" xmi:id="_i0WwGoWXEe6BzrUxPUfMWg" name="60000" content="60000" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_i0WwG4WXEe6BzrUxPUfMWg" key="connection_timeout_ms">
                <expression xmi:type="expression:Expression" xmi:id="_i0WwHIWXEe6BzrUxPUfMWg" name="60000" content="60000" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_i0WwHYWXEe6BzrUxPUfMWg" key="trust_strategy">
                <expression xmi:type="expression:Expression" xmi:id="_i0WwHoWXEe6BzrUxPUfMWg" name="DEFAULT" content="DEFAULT" returnTypeFixed="true"/>
              </parameters>
            </configuration>
            <outputs xmi:type="expression:Operation" xmi:id="_i0WwH4WXEe6BzrUxPUfMWg">
              <leftOperand xmi:type="expression:Expression" xmi:id="_i0WwIIWXEe6BzrUxPUfMWg"/>
              <rightOperand xmi:type="expression:Expression" xmi:id="_i0WwIYWXEe6BzrUxPUfMWg" name="bodyAsString" content="bodyAsString" type="CONNECTOR_OUTPUT_TYPE">
                <referencedElements xmi:type="definition:Output" xmi:id="_i0WwIoWXEe6BzrUxPUfMWg" name="bodyAsString" type="java.lang.String"/>
              </rightOperand>
              <operator xmi:type="expression:Operator" xmi:id="_i0WwI4WXEe6BzrUxPUfMWg" type="ASSIGNMENT"/>
            </outputs>
            <outputs xmi:type="expression:Operation" xmi:id="_i0WwJIWXEe6BzrUxPUfMWg">
              <leftOperand xmi:type="expression:Expression" xmi:id="_i0WwJYWXEe6BzrUxPUfMWg"/>
              <rightOperand xmi:type="expression:Expression" xmi:id="_i0WwJoWXEe6BzrUxPUfMWg" name="bodyAsObject" content="bodyAsObject" type="CONNECTOR_OUTPUT_TYPE" returnType="java.lang.Object">
                <referencedElements xmi:type="definition:Output" xmi:id="_i0WwJ4WXEe6BzrUxPUfMWg" name="bodyAsObject" type="java.lang.Object"/>
              </rightOperand>
              <operator xmi:type="expression:Operator" xmi:id="_i0WwKIWXEe6BzrUxPUfMWg" type="ASSIGNMENT"/>
            </outputs>
            <outputs xmi:type="expression:Operation" xmi:id="_i0WwKYWXEe6BzrUxPUfMWg">
              <leftOperand xmi:type="expression:Expression" xmi:id="_i0WwKoWXEe6BzrUxPUfMWg"/>
              <rightOperand xmi:type="expression:Expression" xmi:id="_i0WwK4WXEe6BzrUxPUfMWg" name="headers" content="headers" type="CONNECTOR_OUTPUT_TYPE" returnType="java.util.Map">
                <referencedElements xmi:type="definition:Output" xmi:id="_i0WwLIWXEe6BzrUxPUfMWg" name="headers" type="java.util.Map"/>
              </rightOperand>
              <operator xmi:type="expression:Operator" xmi:id="_i0WwLYWXEe6BzrUxPUfMWg" type="ASSIGNMENT"/>
            </outputs>
            <outputs xmi:type="expression:Operation" xmi:id="_i0WwLoWXEe6BzrUxPUfMWg">
              <leftOperand xmi:type="expression:Expression" xmi:id="_i0WwL4WXEe6BzrUxPUfMWg"/>
              <rightOperand xmi:type="expression:Expression" xmi:id="_i0WwMIWXEe6BzrUxPUfMWg" name="status_code" content="status_code" type="CONNECTOR_OUTPUT_TYPE" returnType="java.lang.Integer">
                <referencedElements xmi:type="definition:Output" xmi:id="_i0WwMYWXEe6BzrUxPUfMWg" name="status_code" type="java.lang.Integer"/>
              </rightOperand>
              <operator xmi:type="expression:Operator" xmi:id="_i0WwMoWXEe6BzrUxPUfMWg" type="ASSIGNMENT"/>
            </outputs>
            <outputs xmi:type="expression:Operation" xmi:id="_i0WwM4WXEe6BzrUxPUfMWg">
              <leftOperand xmi:type="expression:Expression" xmi:id="_i0WwNIWXEe6BzrUxPUfMWg"/>
              <rightOperand xmi:type="expression:Expression" xmi:id="_i0WwNYWXEe6BzrUxPUfMWg" name="status_message" content="status_message" type="CONNECTOR_OUTPUT_TYPE">
                <referencedElements xmi:type="definition:Output" xmi:id="_i0WwNoWXEe6BzrUxPUfMWg" name="status_message" type="java.lang.String"/>
              </rightOperand>
              <operator xmi:type="expression:Operator" xmi:id="_i0WwN4WXEe6BzrUxPUfMWg" type="ASSIGNMENT"/>
            </outputs>
          </connectors>
          <connectors xmi:type="process:Connector" xmi:id="_C2ekAIVVEe6tqtrNPEic8A" name="Verify Dukcapil" definitionId="rest-get" event="ON_ENTER" definitionVersion="1.2.0">
            <configuration xmi:type="connectorconfiguration:ConnectorConfiguration" xmi:id="_C2ekAYVVEe6tqtrNPEic8A" definitionId="rest-get" version="1.2.0" modelVersion="7.12.0-004">
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_C2ekAoVVEe6tqtrNPEic8A" key="url">
                <expression xmi:type="expression:Expression" xmi:id="_C2ekA4VVEe6tqtrNPEic8A" name="url()" content="baseUrl_dukcapil+'/dukcapil/verify?nik='+passanger.id_number" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnTypeFixed="true">
                  <referencedElements xmi:type="parameter:Parameter" xmi:id="_JSAwAIb1Ee6NpJx4hoX1Ww" name="baseUrl_dukcapil" typeClassname="java.lang.String"/>
                  <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_JSAwAYb1Ee6NpJx4hoX1Ww" name="passanger" dataType="_0Zm0U4U7Ee60zYC5i_hnmg" className="fww.model.Passanger"/>
                </expression>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_C2ekBoVVEe6tqtrNPEic8A" key="urlCookies">
                <expression xmi:type="expression:TableExpression" xmi:id="_C2ekB4VVEe6tqtrNPEic8A"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_C2ekCIVVEe6tqtrNPEic8A" key="urlHeaders">
                <expression xmi:type="expression:TableExpression" xmi:id="_C2ekCYVVEe6tqtrNPEic8A"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_C2ekCoVVEe6tqtrNPEic8A" key="do_not_follow_redirect">
                <expression xmi:type="expression:Expression" xmi:id="_C2ekC4VVEe6tqtrNPEic8A" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_C2ekDIVVEe6tqtrNPEic8A" key="ignore_body">
                <expression xmi:type="expression:Expression" xmi:id="_C2ekDYVVEe6tqtrNPEic8A" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_C2ekDoVVEe6tqtrNPEic8A" key="TLS">
                <expression xmi:type="expression:Expression" xmi:id="_C2ekD4VVEe6tqtrNPEic8A" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_C2ekEIVVEe6tqtrNPEic8A" key="hostname_verifier">
                <expression xmi:type="expression:Expression" xmi:id="_C2ekEYVVEe6tqtrNPEic8A" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_C2ekEoVVEe6tqtrNPEic8A" key="trust_store_file">
                <expression xmi:type="expression:Expression" xmi:id="_C2ekE4VVEe6tqtrNPEic8A" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_C2ekFIVVEe6tqtrNPEic8A" key="trust_store_password">
                <expression xmi:type="expression:Expression" xmi:id="_C2ekFYVVEe6tqtrNPEic8A" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_C2ekFoVVEe6tqtrNPEic8A" key="key_store_file">
                <expression xmi:type="expression:Expression" xmi:id="_C2ekF4VVEe6tqtrNPEic8A" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_C2ekGIVVEe6tqtrNPEic8A" key="key_store_password">
                <expression xmi:type="expression:Expression" xmi:id="_C2ekGYVVEe6tqtrNPEic8A" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_C2ekGoVVEe6tqtrNPEic8A" key="auth_type">
                <expression xmi:type="expression:Expression" xmi:id="_C2ekG4VVEe6tqtrNPEic8A" name="NONE" content="NONE" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_C2ekHIVVEe6tqtrNPEic8A" key="auth_username">
                <expression xmi:type="expression:Expression" xmi:id="_C2ekHYVVEe6tqtrNPEic8A" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_C2ekHoVVEe6tqtrNPEic8A" key="auth_password">
                <expression xmi:type="expression:Expression" xmi:id="_C2ekH4VVEe6tqtrNPEic8A" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_C2ekIIVVEe6tqtrNPEic8A" key="auth_host">
                <expression xmi:type="expression:Expression" xmi:id="_C2ekIYVVEe6tqtrNPEic8A" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_C2ekIoVVEe6tqtrNPEic8A" key="auth_port">
                <expression xmi:type="expression:Expression" xmi:id="_C2ekI4VVEe6tqtrNPEic8A" name="-1" content="-1" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_C2ekJIVVEe6tqtrNPEic8A" key="auth_realm">
                <expression xmi:type="expression:Expression" xmi:id="_C2ekJYVVEe6tqtrNPEic8A" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_C2ekJoVVEe6tqtrNPEic8A" key="auth_preemptive">
                <expression xmi:type="expression:Expression" xmi:id="_C2ekJ4VVEe6tqtrNPEic8A" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_C2ekKIVVEe6tqtrNPEic8A" key="proxy_protocol">
                <expression xmi:type="expression:Expression" xmi:id="_C2ekKYVVEe6tqtrNPEic8A" name="HTTP" content="HTTP" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_C2ekKoVVEe6tqtrNPEic8A" key="proxy_host">
                <expression xmi:type="expression:Expression" xmi:id="_C2ekK4VVEe6tqtrNPEic8A" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_C2ekLIVVEe6tqtrNPEic8A" key="proxy_port">
                <expression xmi:type="expression:Expression" xmi:id="_C2ekLYVVEe6tqtrNPEic8A" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_C2ekLoVVEe6tqtrNPEic8A" key="proxy_username">
                <expression xmi:type="expression:Expression" xmi:id="_C2ekL4VVEe6tqtrNPEic8A" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_C2ekMIVVEe6tqtrNPEic8A" key="proxy_password">
                <expression xmi:type="expression:Expression" xmi:id="_C2ekMYVVEe6tqtrNPEic8A" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_C2ekMoVVEe6tqtrNPEic8A" key="socket_timeout_ms">
                <expression xmi:type="expression:Expression" xmi:id="_C2ekM4VVEe6tqtrNPEic8A" name="60000" content="60000" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_C2ekNIVVEe6tqtrNPEic8A" key="connection_timeout_ms">
                <expression xmi:type="expression:Expression" xmi:id="_C2ekNYVVEe6tqtrNPEic8A" name="60000" content="60000" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_C2ekNoVVEe6tqtrNPEic8A" key="trust_strategy">
                <expression xmi:type="expression:Expression" xmi:id="_C2ekN4VVEe6tqtrNPEic8A" name="DEFAULT" content="DEFAULT" returnTypeFixed="true"/>
              </parameters>
            </configuration>
            <outputs xmi:type="expression:Operation" xmi:id="_C2ekOIVVEe6tqtrNPEic8A">
              <leftOperand xmi:type="expression:Expression" xmi:id="_C2ekOYVVEe6tqtrNPEic8A" name="passanger" content="passanger" type="TYPE_VARIABLE" returnType="fww.model.Passanger">
                <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_jpHVAIWUEe6BzrUxPUfMWg" name="passanger" dataType="_0Zm0U4U7Ee60zYC5i_hnmg" className="fww.model.Passanger"/>
              </leftOperand>
              <rightOperand xmi:type="expression:Expression" xmi:id="_C2ekOoVVEe6tqtrNPEic8A" name="newScript()" content="return bodyAsObject.status" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean">
                <referencedElements xmi:type="definition:Output" xmi:id="_6letUIb4Ee6NpJx4hoX1Ww" name="bodyAsObject" type="java.lang.Object"/>
              </rightOperand>
              <operator xmi:type="expression:Operator" xmi:id="_C2ekPIVVEe6tqtrNPEic8A" type="JAVA_METHOD" expression="setIs_verified_dukcapil">
                <inputTypes>java.lang.Boolean</inputTypes>
              </operator>
            </outputs>
            <outputs xmi:type="expression:Operation" xmi:id="_C2ekPYVVEe6tqtrNPEic8A">
              <leftOperand xmi:type="expression:Expression" xmi:id="_C2ekPoVVEe6tqtrNPEic8A"/>
              <rightOperand xmi:type="expression:Expression" xmi:id="_C2ekP4VVEe6tqtrNPEic8A" name="bodyAsObject" content="bodyAsObject" type="CONNECTOR_OUTPUT_TYPE" returnType="java.lang.Object">
                <referencedElements xmi:type="definition:Output" xmi:id="_C2ekQIVVEe6tqtrNPEic8A" name="bodyAsObject" type="java.lang.Object"/>
              </rightOperand>
              <operator xmi:type="expression:Operator" xmi:id="_C2ekQYVVEe6tqtrNPEic8A" type="ASSIGNMENT"/>
            </outputs>
            <outputs xmi:type="expression:Operation" xmi:id="_C2ekQoVVEe6tqtrNPEic8A">
              <leftOperand xmi:type="expression:Expression" xmi:id="_C2ekQ4VVEe6tqtrNPEic8A"/>
              <rightOperand xmi:type="expression:Expression" xmi:id="_C2ekRIVVEe6tqtrNPEic8A" name="headers" content="headers" type="CONNECTOR_OUTPUT_TYPE" returnType="java.util.Map">
                <referencedElements xmi:type="definition:Output" xmi:id="_C2ekRYVVEe6tqtrNPEic8A" name="headers" type="java.util.Map"/>
              </rightOperand>
              <operator xmi:type="expression:Operator" xmi:id="_C2ekRoVVEe6tqtrNPEic8A" type="ASSIGNMENT"/>
            </outputs>
            <outputs xmi:type="expression:Operation" xmi:id="_C2ekR4VVEe6tqtrNPEic8A">
              <leftOperand xmi:type="expression:Expression" xmi:id="_C2ekSIVVEe6tqtrNPEic8A"/>
              <rightOperand xmi:type="expression:Expression" xmi:id="_C2ekSYVVEe6tqtrNPEic8A" name="status_code" content="status_code" type="CONNECTOR_OUTPUT_TYPE" returnType="java.lang.Integer">
                <referencedElements xmi:type="definition:Output" xmi:id="_C2ekSoVVEe6tqtrNPEic8A" name="status_code" type="java.lang.Integer"/>
              </rightOperand>
              <operator xmi:type="expression:Operator" xmi:id="_C2ekS4VVEe6tqtrNPEic8A" type="ASSIGNMENT"/>
            </outputs>
            <outputs xmi:type="expression:Operation" xmi:id="_C2ekTIVVEe6tqtrNPEic8A">
              <leftOperand xmi:type="expression:Expression" xmi:id="_C2ekTYVVEe6tqtrNPEic8A"/>
              <rightOperand xmi:type="expression:Expression" xmi:id="_C2ekToVVEe6tqtrNPEic8A" name="status_message" content="status_message" type="CONNECTOR_OUTPUT_TYPE">
                <referencedElements xmi:type="definition:Output" xmi:id="_C2fLEIVVEe6tqtrNPEic8A" name="status_message" type="java.lang.String"/>
              </rightOperand>
              <operator xmi:type="expression:Operator" xmi:id="_C2fLEYVVEe6tqtrNPEic8A" type="ASSIGNMENT"/>
            </outputs>
          </connectors>
          <loopCondition xmi:type="expression:Expression" xmi:id="_UJtd1IU-Ee6tqtrNPEic8A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_UJuE4IU-Ee6tqtrNPEic8A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_UJuE4YU-Ee6tqtrNPEic8A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_UJuE4oU-Ee6tqtrNPEic8A" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_UJuE44U-Ee6tqtrNPEic8A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_rLTxMIU-Ee6tqtrNPEic8A" name="Update Passenger Dukcapil" outgoing="_vr3LQIU-Ee6tqtrNPEic8A" incoming="_tkeA8IU-Ee6tqtrNPEic8A">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_rLTxMYU-Ee6tqtrNPEic8A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_rLTxMoU-Ee6tqtrNPEic8A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_rLTxM4U-Ee6tqtrNPEic8A" name="" content="" returnTypeFixed="true"/>
          <connectors xmi:type="process:Connector" xmi:id="_olhdQIWXEe6BzrUxPUfMWg" name="Save Workflow" definitionId="rest-post" event="ON_ENTER" definitionVersion="1.3.0">
            <configuration xmi:type="connectorconfiguration:ConnectorConfiguration" xmi:id="_olhdQYWXEe6BzrUxPUfMWg" definitionId="rest-post" version="1.3.0" modelVersion="7.12.0-004">
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_olhdQoWXEe6BzrUxPUfMWg" key="url">
                <expression xmi:type="expression:Expression" xmi:id="_olhdQ4WXEe6BzrUxPUfMWg" name="url()" content="baseUrl_wrapper+'/api/private/v1/workflow'" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnTypeFixed="true">
                  <referencedElements xmi:type="parameter:Parameter" xmi:id="_olhdRIWXEe6BzrUxPUfMWg" name="baseUrl_wrapper" typeClassname="java.lang.String"/>
                </expression>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_olhdRYWXEe6BzrUxPUfMWg" key="contentType">
                <expression xmi:type="expression:Expression" xmi:id="_olhdRoWXEe6BzrUxPUfMWg" name="application/json" content="application/json" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_olhdR4WXEe6BzrUxPUfMWg" key="charset">
                <expression xmi:type="expression:Expression" xmi:id="_olhdSIWXEe6BzrUxPUfMWg" name="UTF-8" content="UTF-8" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_olhdSYWXEe6BzrUxPUfMWg" key="urlCookies">
                <expression xmi:type="expression:TableExpression" xmi:id="_olhdSoWXEe6BzrUxPUfMWg"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_olhdS4WXEe6BzrUxPUfMWg" key="urlHeaders">
                <expression xmi:type="expression:TableExpression" xmi:id="_olhdTIWXEe6BzrUxPUfMWg"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_olhdTYWXEe6BzrUxPUfMWg" key="body">
                <expression xmi:type="expression:Expression" xmi:id="_olhdToWXEe6BzrUxPUfMWg" name="&lt;pattern-expression>" content="{&#xA;&#x9;&quot;case_id&quot;: ${processInstanceId},&#xA;&#x9;&quot;task_name&quot;: &quot;Update Passenger Dukcapil&quot;,&#xA;&#x9;&quot;process_name&quot;: &quot;passenger_flow&quot;&#xA;}" type="TYPE_PATTERN" returnTypeFixed="true">
                  <referencedElements xmi:type="expression:Expression" xmi:id="_tGJIwIWXEe6BzrUxPUfMWg" name="processInstanceId" content="processInstanceId" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
                    <referencedElements xmi:type="expression:Expression" xmi:id="_tGJIwYWXEe6BzrUxPUfMWg" name="processInstanceId" content="processInstanceId" type="TYPE_ENGINE_CONSTANT" returnType="java.lang.Long" returnTypeFixed="true"/>
                  </referencedElements>
                </expression>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_olhdUYWXEe6BzrUxPUfMWg" key="do_not_follow_redirect">
                <expression xmi:type="expression:Expression" xmi:id="_olhdUoWXEe6BzrUxPUfMWg" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_olhdU4WXEe6BzrUxPUfMWg" key="ignore_body">
                <expression xmi:type="expression:Expression" xmi:id="_olhdVIWXEe6BzrUxPUfMWg" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_olhdVYWXEe6BzrUxPUfMWg" key="TLS">
                <expression xmi:type="expression:Expression" xmi:id="_olhdVoWXEe6BzrUxPUfMWg" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_olhdV4WXEe6BzrUxPUfMWg" key="hostname_verifier">
                <expression xmi:type="expression:Expression" xmi:id="_olhdWIWXEe6BzrUxPUfMWg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_olhdWYWXEe6BzrUxPUfMWg" key="trust_store_file">
                <expression xmi:type="expression:Expression" xmi:id="_olhdWoWXEe6BzrUxPUfMWg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_olhdW4WXEe6BzrUxPUfMWg" key="trust_store_password">
                <expression xmi:type="expression:Expression" xmi:id="_olhdXIWXEe6BzrUxPUfMWg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_olhdXYWXEe6BzrUxPUfMWg" key="key_store_file">
                <expression xmi:type="expression:Expression" xmi:id="_olhdXoWXEe6BzrUxPUfMWg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_olhdX4WXEe6BzrUxPUfMWg" key="key_store_password">
                <expression xmi:type="expression:Expression" xmi:id="_olhdYIWXEe6BzrUxPUfMWg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_olhdYYWXEe6BzrUxPUfMWg" key="auth_type">
                <expression xmi:type="expression:Expression" xmi:id="_olhdYoWXEe6BzrUxPUfMWg" name="NONE" content="NONE" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_olhdY4WXEe6BzrUxPUfMWg" key="auth_username">
                <expression xmi:type="expression:Expression" xmi:id="_olhdZIWXEe6BzrUxPUfMWg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_olhdZYWXEe6BzrUxPUfMWg" key="auth_password">
                <expression xmi:type="expression:Expression" xmi:id="_olhdZoWXEe6BzrUxPUfMWg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_olhdZ4WXEe6BzrUxPUfMWg" key="auth_host">
                <expression xmi:type="expression:Expression" xmi:id="_olhdaIWXEe6BzrUxPUfMWg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_olhdaYWXEe6BzrUxPUfMWg" key="auth_port">
                <expression xmi:type="expression:Expression" xmi:id="_olhdaoWXEe6BzrUxPUfMWg" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_olhda4WXEe6BzrUxPUfMWg" key="auth_realm">
                <expression xmi:type="expression:Expression" xmi:id="_olhdbIWXEe6BzrUxPUfMWg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_olhdbYWXEe6BzrUxPUfMWg" key="auth_preemptive">
                <expression xmi:type="expression:Expression" xmi:id="_olhdboWXEe6BzrUxPUfMWg" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_olhdb4WXEe6BzrUxPUfMWg" key="proxy_protocol">
                <expression xmi:type="expression:Expression" xmi:id="_olhdcIWXEe6BzrUxPUfMWg" name="HTTP" content="HTTP" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_olhdcYWXEe6BzrUxPUfMWg" key="proxy_host">
                <expression xmi:type="expression:Expression" xmi:id="_olhdcoWXEe6BzrUxPUfMWg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_olhdc4WXEe6BzrUxPUfMWg" key="proxy_port">
                <expression xmi:type="expression:Expression" xmi:id="_olhddIWXEe6BzrUxPUfMWg" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_olhddYWXEe6BzrUxPUfMWg" key="proxy_username">
                <expression xmi:type="expression:Expression" xmi:id="_olhddoWXEe6BzrUxPUfMWg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_olhdd4WXEe6BzrUxPUfMWg" key="proxy_password">
                <expression xmi:type="expression:Expression" xmi:id="_olhdeIWXEe6BzrUxPUfMWg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_olhdeYWXEe6BzrUxPUfMWg" key="socket_timeout_ms">
                <expression xmi:type="expression:Expression" xmi:id="_olhdeoWXEe6BzrUxPUfMWg" name="60000" content="60000" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_olhde4WXEe6BzrUxPUfMWg" key="connection_timeout_ms">
                <expression xmi:type="expression:Expression" xmi:id="_olhdfIWXEe6BzrUxPUfMWg" name="60000" content="60000" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_olhdfYWXEe6BzrUxPUfMWg" key="trust_strategy">
                <expression xmi:type="expression:Expression" xmi:id="_olhdfoWXEe6BzrUxPUfMWg" name="DEFAULT" content="DEFAULT" returnTypeFixed="true"/>
              </parameters>
            </configuration>
            <outputs xmi:type="expression:Operation" xmi:id="_olhdf4WXEe6BzrUxPUfMWg">
              <leftOperand xmi:type="expression:Expression" xmi:id="_olhdgIWXEe6BzrUxPUfMWg"/>
              <rightOperand xmi:type="expression:Expression" xmi:id="_olhdgYWXEe6BzrUxPUfMWg" name="bodyAsString" content="bodyAsString" type="CONNECTOR_OUTPUT_TYPE">
                <referencedElements xmi:type="definition:Output" xmi:id="_olhdgoWXEe6BzrUxPUfMWg" name="bodyAsString" type="java.lang.String"/>
              </rightOperand>
              <operator xmi:type="expression:Operator" xmi:id="_olhdg4WXEe6BzrUxPUfMWg" type="ASSIGNMENT"/>
            </outputs>
            <outputs xmi:type="expression:Operation" xmi:id="_olhdhIWXEe6BzrUxPUfMWg">
              <leftOperand xmi:type="expression:Expression" xmi:id="_olhdhYWXEe6BzrUxPUfMWg"/>
              <rightOperand xmi:type="expression:Expression" xmi:id="_olhdhoWXEe6BzrUxPUfMWg" name="bodyAsObject" content="bodyAsObject" type="CONNECTOR_OUTPUT_TYPE" returnType="java.lang.Object">
                <referencedElements xmi:type="definition:Output" xmi:id="_olhdh4WXEe6BzrUxPUfMWg" name="bodyAsObject" type="java.lang.Object"/>
              </rightOperand>
              <operator xmi:type="expression:Operator" xmi:id="_olhdiIWXEe6BzrUxPUfMWg" type="ASSIGNMENT"/>
            </outputs>
            <outputs xmi:type="expression:Operation" xmi:id="_olhdiYWXEe6BzrUxPUfMWg">
              <leftOperand xmi:type="expression:Expression" xmi:id="_olhdioWXEe6BzrUxPUfMWg"/>
              <rightOperand xmi:type="expression:Expression" xmi:id="_olhdi4WXEe6BzrUxPUfMWg" name="headers" content="headers" type="CONNECTOR_OUTPUT_TYPE" returnType="java.util.Map">
                <referencedElements xmi:type="definition:Output" xmi:id="_olhdjIWXEe6BzrUxPUfMWg" name="headers" type="java.util.Map"/>
              </rightOperand>
              <operator xmi:type="expression:Operator" xmi:id="_olhdjYWXEe6BzrUxPUfMWg" type="ASSIGNMENT"/>
            </outputs>
            <outputs xmi:type="expression:Operation" xmi:id="_olhdjoWXEe6BzrUxPUfMWg">
              <leftOperand xmi:type="expression:Expression" xmi:id="_olhdj4WXEe6BzrUxPUfMWg"/>
              <rightOperand xmi:type="expression:Expression" xmi:id="_olhdkIWXEe6BzrUxPUfMWg" name="status_code" content="status_code" type="CONNECTOR_OUTPUT_TYPE" returnType="java.lang.Integer">
                <referencedElements xmi:type="definition:Output" xmi:id="_olhdkYWXEe6BzrUxPUfMWg" name="status_code" type="java.lang.Integer"/>
              </rightOperand>
              <operator xmi:type="expression:Operator" xmi:id="_olhdkoWXEe6BzrUxPUfMWg" type="ASSIGNMENT"/>
            </outputs>
            <outputs xmi:type="expression:Operation" xmi:id="_olhdk4WXEe6BzrUxPUfMWg">
              <leftOperand xmi:type="expression:Expression" xmi:id="_olhdlIWXEe6BzrUxPUfMWg"/>
              <rightOperand xmi:type="expression:Expression" xmi:id="_olhdlYWXEe6BzrUxPUfMWg" name="status_message" content="status_message" type="CONNECTOR_OUTPUT_TYPE">
                <referencedElements xmi:type="definition:Output" xmi:id="_olhdloWXEe6BzrUxPUfMWg" name="status_message" type="java.lang.String"/>
              </rightOperand>
              <operator xmi:type="expression:Operator" xmi:id="_olhdl4WXEe6BzrUxPUfMWg" type="ASSIGNMENT"/>
            </outputs>
          </connectors>
          <connectors xmi:type="process:Connector" xmi:id="_mxhTkIWYEe6BzrUxPUfMWg" name="Update Passenger" definitionId="rest-put" event="ON_ENTER" definitionVersion="1.3.0">
            <configuration xmi:type="connectorconfiguration:ConnectorConfiguration" xmi:id="_mxhTkYWYEe6BzrUxPUfMWg" definitionId="rest-put" version="1.3.0" modelVersion="7.12.0-004">
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_mxhTkoWYEe6BzrUxPUfMWg" key="url">
                <expression xmi:type="expression:Expression" xmi:id="_mxhTk4WYEe6BzrUxPUfMWg" name="url()" content="baseUrl_wrapper+'/api/private/v1/passenger'" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnTypeFixed="true">
                  <referencedElements xmi:type="parameter:Parameter" xmi:id="_mxhTlIWYEe6BzrUxPUfMWg" name="baseUrl_wrapper" typeClassname="java.lang.String"/>
                </expression>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_mxhTlYWYEe6BzrUxPUfMWg" key="contentType">
                <expression xmi:type="expression:Expression" xmi:id="_mxhTloWYEe6BzrUxPUfMWg" name="application/json" content="application/json" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_mxhTl4WYEe6BzrUxPUfMWg" key="charset">
                <expression xmi:type="expression:Expression" xmi:id="_mxhTmIWYEe6BzrUxPUfMWg" name="UTF-8" content="UTF-8" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_mxhTmYWYEe6BzrUxPUfMWg" key="urlCookies">
                <expression xmi:type="expression:TableExpression" xmi:id="_mxhTmoWYEe6BzrUxPUfMWg"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_mxhTm4WYEe6BzrUxPUfMWg" key="urlHeaders">
                <expression xmi:type="expression:TableExpression" xmi:id="_mxhTnIWYEe6BzrUxPUfMWg"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_mxhTnYWYEe6BzrUxPUfMWg" key="body">
                <expression xmi:type="expression:Expression" xmi:id="_mxhTnoWYEe6BzrUxPUfMWg" name="&lt;pattern-expression>" content="{&#xA;&#x9;&quot;id_number&quot;: &quot;${passanger.id_number}&quot;,&#xA;&#x9;&quot;is_verified_dukcapil&quot;: ${passanger.is_verified_dukcapil},&#xA;&#x9;&quot;case_id&quot;: ${processInstanceId}&#xA;}" type="TYPE_PATTERN" returnTypeFixed="true">
                  <referencedElements xmi:type="expression:Expression" xmi:id="_8rYTwIcBEe6NpJx4hoX1Ww" name="passanger.id_number" content="passanger.id_number" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
                    <referencedElements xmi:type="expression:Expression" xmi:id="_8rYTwYcBEe6NpJx4hoX1Ww" name="passanger" content="passanger" type="TYPE_VARIABLE" returnType="fww.model.Passanger">
                      <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_8rYTwocBEe6NpJx4hoX1Ww" name="passanger" dataType="_0Zm0U4U7Ee60zYC5i_hnmg" className="fww.model.Passanger"/>
                    </referencedElements>
                  </referencedElements>
                  <referencedElements xmi:type="expression:Expression" xmi:id="_8rYTw4cBEe6NpJx4hoX1Ww" name="passanger.is_verified_dukcapil" content="passanger.is_verified_dukcapil" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
                    <referencedElements xmi:type="expression:Expression" xmi:id="_8rYTxIcBEe6NpJx4hoX1Ww" name="passanger" content="passanger" type="TYPE_VARIABLE" returnType="fww.model.Passanger">
                      <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_8rYTxYcBEe6NpJx4hoX1Ww" name="passanger" dataType="_0Zm0U4U7Ee60zYC5i_hnmg" className="fww.model.Passanger"/>
                    </referencedElements>
                  </referencedElements>
                  <referencedElements xmi:type="expression:Expression" xmi:id="_8rYTxocBEe6NpJx4hoX1Ww" name="processInstanceId" content="processInstanceId" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
                    <referencedElements xmi:type="expression:Expression" xmi:id="_8rYTx4cBEe6NpJx4hoX1Ww" name="processInstanceId" content="processInstanceId" type="TYPE_ENGINE_CONSTANT" returnType="java.lang.Long" returnTypeFixed="true"/>
                  </referencedElements>
                </expression>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_mxhTqoWYEe6BzrUxPUfMWg" key="do_not_follow_redirect">
                <expression xmi:type="expression:Expression" xmi:id="_mxhTq4WYEe6BzrUxPUfMWg" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_mxhTrIWYEe6BzrUxPUfMWg" key="ignore_body">
                <expression xmi:type="expression:Expression" xmi:id="_mxhTrYWYEe6BzrUxPUfMWg" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_mxhTroWYEe6BzrUxPUfMWg" key="TLS">
                <expression xmi:type="expression:Expression" xmi:id="_mxhTr4WYEe6BzrUxPUfMWg" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_mxhTsIWYEe6BzrUxPUfMWg" key="hostname_verifier">
                <expression xmi:type="expression:Expression" xmi:id="_mxhTsYWYEe6BzrUxPUfMWg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_mxhTsoWYEe6BzrUxPUfMWg" key="trust_store_file">
                <expression xmi:type="expression:Expression" xmi:id="_mxhTs4WYEe6BzrUxPUfMWg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_mxhTtIWYEe6BzrUxPUfMWg" key="trust_store_password">
                <expression xmi:type="expression:Expression" xmi:id="_mxhTtYWYEe6BzrUxPUfMWg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_mxhTtoWYEe6BzrUxPUfMWg" key="key_store_file">
                <expression xmi:type="expression:Expression" xmi:id="_mxhTt4WYEe6BzrUxPUfMWg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_mxhTuIWYEe6BzrUxPUfMWg" key="key_store_password">
                <expression xmi:type="expression:Expression" xmi:id="_mxhTuYWYEe6BzrUxPUfMWg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_mxhTuoWYEe6BzrUxPUfMWg" key="auth_type">
                <expression xmi:type="expression:Expression" xmi:id="_mxhTu4WYEe6BzrUxPUfMWg" name="NONE" content="NONE" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_mxhTvIWYEe6BzrUxPUfMWg" key="auth_username">
                <expression xmi:type="expression:Expression" xmi:id="_mxhTvYWYEe6BzrUxPUfMWg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_mxhTvoWYEe6BzrUxPUfMWg" key="auth_password">
                <expression xmi:type="expression:Expression" xmi:id="_mxhTv4WYEe6BzrUxPUfMWg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_mxhTwIWYEe6BzrUxPUfMWg" key="auth_host">
                <expression xmi:type="expression:Expression" xmi:id="_mxhTwYWYEe6BzrUxPUfMWg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_mxhTwoWYEe6BzrUxPUfMWg" key="auth_port">
                <expression xmi:type="expression:Expression" xmi:id="_mxhTw4WYEe6BzrUxPUfMWg" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_mxhTxIWYEe6BzrUxPUfMWg" key="auth_realm">
                <expression xmi:type="expression:Expression" xmi:id="_mxhTxYWYEe6BzrUxPUfMWg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_mxhTxoWYEe6BzrUxPUfMWg" key="auth_preemptive">
                <expression xmi:type="expression:Expression" xmi:id="_mxhTx4WYEe6BzrUxPUfMWg" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_mxhTyIWYEe6BzrUxPUfMWg" key="proxy_protocol">
                <expression xmi:type="expression:Expression" xmi:id="_mxhTyYWYEe6BzrUxPUfMWg" name="HTTP" content="HTTP" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_mxhTyoWYEe6BzrUxPUfMWg" key="proxy_host">
                <expression xmi:type="expression:Expression" xmi:id="_mxhTy4WYEe6BzrUxPUfMWg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_mxhTzIWYEe6BzrUxPUfMWg" key="proxy_port">
                <expression xmi:type="expression:Expression" xmi:id="_mxhTzYWYEe6BzrUxPUfMWg" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_mxhTzoWYEe6BzrUxPUfMWg" key="proxy_username">
                <expression xmi:type="expression:Expression" xmi:id="_mxhTz4WYEe6BzrUxPUfMWg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_mxhT0IWYEe6BzrUxPUfMWg" key="proxy_password">
                <expression xmi:type="expression:Expression" xmi:id="_mxhT0YWYEe6BzrUxPUfMWg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_mxhT0oWYEe6BzrUxPUfMWg" key="socket_timeout_ms">
                <expression xmi:type="expression:Expression" xmi:id="_mxhT04WYEe6BzrUxPUfMWg" name="60000" content="60000" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_mxhT1IWYEe6BzrUxPUfMWg" key="connection_timeout_ms">
                <expression xmi:type="expression:Expression" xmi:id="_mxhT1YWYEe6BzrUxPUfMWg" name="60000" content="60000" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_mxhT1oWYEe6BzrUxPUfMWg" key="trust_strategy">
                <expression xmi:type="expression:Expression" xmi:id="_mxhT14WYEe6BzrUxPUfMWg" name="DEFAULT" content="DEFAULT" returnTypeFixed="true"/>
              </parameters>
            </configuration>
            <outputs xmi:type="expression:Operation" xmi:id="_mxhT2IWYEe6BzrUxPUfMWg">
              <leftOperand xmi:type="expression:Expression" xmi:id="_mxhT2YWYEe6BzrUxPUfMWg"/>
              <rightOperand xmi:type="expression:Expression" xmi:id="_mxhT2oWYEe6BzrUxPUfMWg" name="bodyAsString" content="bodyAsString" type="CONNECTOR_OUTPUT_TYPE">
                <referencedElements xmi:type="definition:Output" xmi:id="_mxhT24WYEe6BzrUxPUfMWg" name="bodyAsString" type="java.lang.String"/>
              </rightOperand>
              <operator xmi:type="expression:Operator" xmi:id="_mxhT3IWYEe6BzrUxPUfMWg" type="ASSIGNMENT"/>
            </outputs>
            <outputs xmi:type="expression:Operation" xmi:id="_mxhT3YWYEe6BzrUxPUfMWg">
              <leftOperand xmi:type="expression:Expression" xmi:id="_mxhT3oWYEe6BzrUxPUfMWg"/>
              <rightOperand xmi:type="expression:Expression" xmi:id="_mxhT34WYEe6BzrUxPUfMWg" name="bodyAsObject" content="bodyAsObject" type="CONNECTOR_OUTPUT_TYPE" returnType="java.lang.Object">
                <referencedElements xmi:type="definition:Output" xmi:id="_mxhT4IWYEe6BzrUxPUfMWg" name="bodyAsObject" type="java.lang.Object"/>
              </rightOperand>
              <operator xmi:type="expression:Operator" xmi:id="_mxhT4YWYEe6BzrUxPUfMWg" type="ASSIGNMENT"/>
            </outputs>
            <outputs xmi:type="expression:Operation" xmi:id="_mxhT4oWYEe6BzrUxPUfMWg">
              <leftOperand xmi:type="expression:Expression" xmi:id="_mxhT44WYEe6BzrUxPUfMWg"/>
              <rightOperand xmi:type="expression:Expression" xmi:id="_mxhT5IWYEe6BzrUxPUfMWg" name="headers" content="headers" type="CONNECTOR_OUTPUT_TYPE" returnType="java.util.Map">
                <referencedElements xmi:type="definition:Output" xmi:id="_mxhT5YWYEe6BzrUxPUfMWg" name="headers" type="java.util.Map"/>
              </rightOperand>
              <operator xmi:type="expression:Operator" xmi:id="_mxhT5oWYEe6BzrUxPUfMWg" type="ASSIGNMENT"/>
            </outputs>
            <outputs xmi:type="expression:Operation" xmi:id="_mxhT54WYEe6BzrUxPUfMWg">
              <leftOperand xmi:type="expression:Expression" xmi:id="_mxhT6IWYEe6BzrUxPUfMWg"/>
              <rightOperand xmi:type="expression:Expression" xmi:id="_mxhT6YWYEe6BzrUxPUfMWg" name="status_code" content="status_code" type="CONNECTOR_OUTPUT_TYPE" returnType="java.lang.Integer">
                <referencedElements xmi:type="definition:Output" xmi:id="_mxhT6oWYEe6BzrUxPUfMWg" name="status_code" type="java.lang.Integer"/>
              </rightOperand>
              <operator xmi:type="expression:Operator" xmi:id="_mxhT64WYEe6BzrUxPUfMWg" type="ASSIGNMENT"/>
            </outputs>
            <outputs xmi:type="expression:Operation" xmi:id="_mxhT7IWYEe6BzrUxPUfMWg">
              <leftOperand xmi:type="expression:Expression" xmi:id="_mxhT7YWYEe6BzrUxPUfMWg"/>
              <rightOperand xmi:type="expression:Expression" xmi:id="_mxhT7oWYEe6BzrUxPUfMWg" name="status_message" content="status_message" type="CONNECTOR_OUTPUT_TYPE">
                <referencedElements xmi:type="definition:Output" xmi:id="_mxhT74WYEe6BzrUxPUfMWg" name="status_message" type="java.lang.String"/>
              </rightOperand>
              <operator xmi:type="expression:Operator" xmi:id="_mxhT8IWYEe6BzrUxPUfMWg" type="ASSIGNMENT"/>
            </outputs>
          </connectors>
          <loopCondition xmi:type="expression:Expression" xmi:id="_rLTxNIU-Ee6tqtrNPEic8A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_rLTxNYU-Ee6tqtrNPEic8A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_rLTxNoU-Ee6tqtrNPEic8A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_rLTxN4U-Ee6tqtrNPEic8A" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_rLUYQIU-Ee6tqtrNPEic8A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_1KyFYIbbEe6NpJx4hoX1Ww" name="Close Process" outgoing="_4o05kIbbEe6NpJx4hoX1Ww" incoming="_4NvgEIbbEe6NpJx4hoX1Ww">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_1K9EgYbbEe6NpJx4hoX1Ww" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_1K9EgIbbEe6NpJx4hoX1Ww" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_1K9EgobbEe6NpJx4hoX1Ww" name="" content="" returnTypeFixed="true"/>
          <connectors xmi:type="process:Connector" xmi:id="_lCNukIWXEe6BzrUxPUfMWg" name="Save Workflow" definitionId="rest-post" event="ON_ENTER" definitionVersion="1.3.0">
            <configuration xmi:type="connectorconfiguration:ConnectorConfiguration" xmi:id="_lCNukYWXEe6BzrUxPUfMWg" definitionId="rest-post" version="1.3.0" modelVersion="7.12.0-004">
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_lCNukoWXEe6BzrUxPUfMWg" key="url">
                <expression xmi:type="expression:Expression" xmi:id="_lCNuk4WXEe6BzrUxPUfMWg" name="url()" content="baseUrl_wrapper+'/api/private/v1/workflow'" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnTypeFixed="true">
                  <referencedElements xmi:type="parameter:Parameter" xmi:id="_lCNulIWXEe6BzrUxPUfMWg" name="baseUrl_wrapper" typeClassname="java.lang.String"/>
                </expression>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_lCNulYWXEe6BzrUxPUfMWg" key="contentType">
                <expression xmi:type="expression:Expression" xmi:id="_lCNuloWXEe6BzrUxPUfMWg" name="application/json" content="application/json" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_lCNul4WXEe6BzrUxPUfMWg" key="charset">
                <expression xmi:type="expression:Expression" xmi:id="_lCNumIWXEe6BzrUxPUfMWg" name="UTF-8" content="UTF-8" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_lCNumYWXEe6BzrUxPUfMWg" key="urlCookies">
                <expression xmi:type="expression:TableExpression" xmi:id="_lCNumoWXEe6BzrUxPUfMWg"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_lCNum4WXEe6BzrUxPUfMWg" key="urlHeaders">
                <expression xmi:type="expression:TableExpression" xmi:id="_lCNunIWXEe6BzrUxPUfMWg"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_lCNunYWXEe6BzrUxPUfMWg" key="body">
                <expression xmi:type="expression:Expression" xmi:id="_lCNunoWXEe6BzrUxPUfMWg" name="&lt;pattern-expression>" content="{&#xA;&#x9;&quot;case_id&quot;: ${processInstanceId},&#xA;&#x9;&quot;task_name&quot;: &quot;Close Process&quot;,&#xA;&#x9;&quot;process_name&quot;: &quot;passenger_flow&quot;,&#xA;&#x9;&quot;is_active&quot;: false&#xA;}" type="TYPE_PATTERN" returnTypeFixed="true">
                  <referencedElements xmi:type="expression:Expression" xmi:id="_FMeAUIbcEe6NpJx4hoX1Ww" name="processInstanceId" content="processInstanceId" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
                    <referencedElements xmi:type="expression:Expression" xmi:id="_FMeAUYbcEe6NpJx4hoX1Ww" name="processInstanceId" content="processInstanceId" type="TYPE_ENGINE_CONSTANT" returnType="java.lang.Long" returnTypeFixed="true"/>
                  </referencedElements>
                </expression>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_lCNuoYWXEe6BzrUxPUfMWg" key="do_not_follow_redirect">
                <expression xmi:type="expression:Expression" xmi:id="_lCNuooWXEe6BzrUxPUfMWg" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_lCNuo4WXEe6BzrUxPUfMWg" key="ignore_body">
                <expression xmi:type="expression:Expression" xmi:id="_lCNupIWXEe6BzrUxPUfMWg" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_lCNupYWXEe6BzrUxPUfMWg" key="TLS">
                <expression xmi:type="expression:Expression" xmi:id="_lCNupoWXEe6BzrUxPUfMWg" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_lCNup4WXEe6BzrUxPUfMWg" key="hostname_verifier">
                <expression xmi:type="expression:Expression" xmi:id="_lCNuqIWXEe6BzrUxPUfMWg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_lCNuqYWXEe6BzrUxPUfMWg" key="trust_store_file">
                <expression xmi:type="expression:Expression" xmi:id="_lCNuqoWXEe6BzrUxPUfMWg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_lCNuq4WXEe6BzrUxPUfMWg" key="trust_store_password">
                <expression xmi:type="expression:Expression" xmi:id="_lCNurIWXEe6BzrUxPUfMWg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_lCNurYWXEe6BzrUxPUfMWg" key="key_store_file">
                <expression xmi:type="expression:Expression" xmi:id="_lCNuroWXEe6BzrUxPUfMWg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_lCNur4WXEe6BzrUxPUfMWg" key="key_store_password">
                <expression xmi:type="expression:Expression" xmi:id="_lCNusIWXEe6BzrUxPUfMWg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_lCNusYWXEe6BzrUxPUfMWg" key="auth_type">
                <expression xmi:type="expression:Expression" xmi:id="_lCNusoWXEe6BzrUxPUfMWg" name="NONE" content="NONE" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_lCNus4WXEe6BzrUxPUfMWg" key="auth_username">
                <expression xmi:type="expression:Expression" xmi:id="_lCNutIWXEe6BzrUxPUfMWg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_lCNutYWXEe6BzrUxPUfMWg" key="auth_password">
                <expression xmi:type="expression:Expression" xmi:id="_lCNutoWXEe6BzrUxPUfMWg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_lCNut4WXEe6BzrUxPUfMWg" key="auth_host">
                <expression xmi:type="expression:Expression" xmi:id="_lCNuuIWXEe6BzrUxPUfMWg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_lCNuuYWXEe6BzrUxPUfMWg" key="auth_port">
                <expression xmi:type="expression:Expression" xmi:id="_lCNuuoWXEe6BzrUxPUfMWg" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_lCNuu4WXEe6BzrUxPUfMWg" key="auth_realm">
                <expression xmi:type="expression:Expression" xmi:id="_lCNuvIWXEe6BzrUxPUfMWg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_lCNuvYWXEe6BzrUxPUfMWg" key="auth_preemptive">
                <expression xmi:type="expression:Expression" xmi:id="_lCNuvoWXEe6BzrUxPUfMWg" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_lCNuv4WXEe6BzrUxPUfMWg" key="proxy_protocol">
                <expression xmi:type="expression:Expression" xmi:id="_lCNuwIWXEe6BzrUxPUfMWg" name="HTTP" content="HTTP" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_lCNuwYWXEe6BzrUxPUfMWg" key="proxy_host">
                <expression xmi:type="expression:Expression" xmi:id="_lCNuwoWXEe6BzrUxPUfMWg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_lCNuw4WXEe6BzrUxPUfMWg" key="proxy_port">
                <expression xmi:type="expression:Expression" xmi:id="_lCNuxIWXEe6BzrUxPUfMWg" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_lCNuxYWXEe6BzrUxPUfMWg" key="proxy_username">
                <expression xmi:type="expression:Expression" xmi:id="_lCNuxoWXEe6BzrUxPUfMWg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_lCNux4WXEe6BzrUxPUfMWg" key="proxy_password">
                <expression xmi:type="expression:Expression" xmi:id="_lCNuyIWXEe6BzrUxPUfMWg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_lCNuyYWXEe6BzrUxPUfMWg" key="socket_timeout_ms">
                <expression xmi:type="expression:Expression" xmi:id="_lCNuyoWXEe6BzrUxPUfMWg" name="60000" content="60000" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_lCNuy4WXEe6BzrUxPUfMWg" key="connection_timeout_ms">
                <expression xmi:type="expression:Expression" xmi:id="_lCNuzIWXEe6BzrUxPUfMWg" name="60000" content="60000" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_lCNuzYWXEe6BzrUxPUfMWg" key="trust_strategy">
                <expression xmi:type="expression:Expression" xmi:id="_lCNuzoWXEe6BzrUxPUfMWg" name="DEFAULT" content="DEFAULT" returnTypeFixed="true"/>
              </parameters>
            </configuration>
            <outputs xmi:type="expression:Operation" xmi:id="_lCNuz4WXEe6BzrUxPUfMWg">
              <leftOperand xmi:type="expression:Expression" xmi:id="_lCNu0IWXEe6BzrUxPUfMWg"/>
              <rightOperand xmi:type="expression:Expression" xmi:id="_lCNu0YWXEe6BzrUxPUfMWg" name="bodyAsString" content="bodyAsString" type="CONNECTOR_OUTPUT_TYPE">
                <referencedElements xmi:type="definition:Output" xmi:id="_lCNu0oWXEe6BzrUxPUfMWg" name="bodyAsString" type="java.lang.String"/>
              </rightOperand>
              <operator xmi:type="expression:Operator" xmi:id="_lCNu04WXEe6BzrUxPUfMWg" type="ASSIGNMENT"/>
            </outputs>
            <outputs xmi:type="expression:Operation" xmi:id="_lCNu1IWXEe6BzrUxPUfMWg">
              <leftOperand xmi:type="expression:Expression" xmi:id="_lCNu1YWXEe6BzrUxPUfMWg"/>
              <rightOperand xmi:type="expression:Expression" xmi:id="_lCNu1oWXEe6BzrUxPUfMWg" name="bodyAsObject" content="bodyAsObject" type="CONNECTOR_OUTPUT_TYPE" returnType="java.lang.Object">
                <referencedElements xmi:type="definition:Output" xmi:id="_lCNu14WXEe6BzrUxPUfMWg" name="bodyAsObject" type="java.lang.Object"/>
              </rightOperand>
              <operator xmi:type="expression:Operator" xmi:id="_lCNu2IWXEe6BzrUxPUfMWg" type="ASSIGNMENT"/>
            </outputs>
            <outputs xmi:type="expression:Operation" xmi:id="_lCNu2YWXEe6BzrUxPUfMWg">
              <leftOperand xmi:type="expression:Expression" xmi:id="_lCNu2oWXEe6BzrUxPUfMWg"/>
              <rightOperand xmi:type="expression:Expression" xmi:id="_lCNu24WXEe6BzrUxPUfMWg" name="headers" content="headers" type="CONNECTOR_OUTPUT_TYPE" returnType="java.util.Map">
                <referencedElements xmi:type="definition:Output" xmi:id="_lCNu3IWXEe6BzrUxPUfMWg" name="headers" type="java.util.Map"/>
              </rightOperand>
              <operator xmi:type="expression:Operator" xmi:id="_lCNu3YWXEe6BzrUxPUfMWg" type="ASSIGNMENT"/>
            </outputs>
            <outputs xmi:type="expression:Operation" xmi:id="_lCNu3oWXEe6BzrUxPUfMWg">
              <leftOperand xmi:type="expression:Expression" xmi:id="_lCNu34WXEe6BzrUxPUfMWg"/>
              <rightOperand xmi:type="expression:Expression" xmi:id="_lCNu4IWXEe6BzrUxPUfMWg" name="status_code" content="status_code" type="CONNECTOR_OUTPUT_TYPE" returnType="java.lang.Integer">
                <referencedElements xmi:type="definition:Output" xmi:id="_lCNu4YWXEe6BzrUxPUfMWg" name="status_code" type="java.lang.Integer"/>
              </rightOperand>
              <operator xmi:type="expression:Operator" xmi:id="_lCNu4oWXEe6BzrUxPUfMWg" type="ASSIGNMENT"/>
            </outputs>
            <outputs xmi:type="expression:Operation" xmi:id="_lCNu44WXEe6BzrUxPUfMWg">
              <leftOperand xmi:type="expression:Expression" xmi:id="_lCNu5IWXEe6BzrUxPUfMWg"/>
              <rightOperand xmi:type="expression:Expression" xmi:id="_lCNu5YWXEe6BzrUxPUfMWg" name="status_message" content="status_message" type="CONNECTOR_OUTPUT_TYPE">
                <referencedElements xmi:type="definition:Output" xmi:id="_lCNu5oWXEe6BzrUxPUfMWg" name="status_message" type="java.lang.String"/>
              </rightOperand>
              <operator xmi:type="expression:Operator" xmi:id="_lCNu54WXEe6BzrUxPUfMWg" type="ASSIGNMENT"/>
            </outputs>
          </connectors>
          <loopCondition xmi:type="expression:Expression" xmi:id="_1K9Eg4bbEe6NpJx4hoX1Ww" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_1K9EhIbbEe6NpJx4hoX1Ww" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_1K9EhYbbEe6NpJx4hoX1Ww" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_1K9Eh4bbEe6NpJx4hoX1Ww" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_1K9EhobbEe6NpJx4hoX1Ww" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
      </elements>
      <data xmi:type="process:BusinessObjectData" xmi:id="_zKBHoIVTEe6tqtrNPEic8A" name="passanger" dataType="_0Zm0U4U7Ee60zYC5i_hnmg" className="fww.model.Passanger">
        <defaultValue xmi:type="expression:Expression" xmi:id="_PXtFYIVUEe6tqtrNPEic8A" name="initPassanger()" content="def passangerVar = new fww.model.Passanger()&#xA;passangerVar.id_number = id_number&#xA;return passangerVar" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="fww.model.Passanger">
          <referencedElements xmi:type="process:ContractInput" xmi:id="_QVMe4Ib1Ee6NpJx4hoX1Ww" name="id_number">
            <mapping xmi:type="process:ContractInputMapping" xmi:id="_QVMe4Yb1Ee6NpJx4hoX1Ww"/>
          </referencedElements>
        </defaultValue>
      </data>
      <formMapping xmi:type="process:FormMapping" xmi:id="_0Zm0M4U7Ee60zYC5i_hnmg" type="NONE">
        <targetForm xmi:type="expression:Expression" xmi:id="_QYPcsIVREe6tqtrNPEic8A" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_0Zm0NYU7Ee60zYC5i_hnmg" type="NONE">
        <targetForm xmi:type="expression:Expression" xmi:id="_0Zm0NoU7Ee60zYC5i_hnmg" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_0Zm0N4U7Ee60zYC5i_hnmg" target="_UJtd0IU-Ee6tqtrNPEic8A" source="_0Zm0IoU7Ee60zYC5i_hnmg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_0Zm0OIU7Ee60zYC5i_hnmg"/>
        <condition xmi:type="expression:Expression" xmi:id="_0Zm0OYU7Ee60zYC5i_hnmg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_OBGLsIU8Ee60zYC5i_hnmg" target="_KHuGYIU8Ee60zYC5i_hnmg" source="_-yn2YIU7Ee60zYC5i_hnmg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_OBGLsYU8Ee60zYC5i_hnmg"/>
        <condition xmi:type="expression:Expression" xmi:id="_OBGLsoU8Ee60zYC5i_hnmg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_tkeA8IU-Ee6tqtrNPEic8A" target="_rLTxMIU-Ee6tqtrNPEic8A" source="_UJtd0IU-Ee6tqtrNPEic8A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_tkeA8YU-Ee6tqtrNPEic8A"/>
        <condition xmi:type="expression:Expression" xmi:id="_tkeA8oU-Ee6tqtrNPEic8A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_vr3LQIU-Ee6tqtrNPEic8A" target="_-yn2YIU7Ee60zYC5i_hnmg" source="_rLTxMIU-Ee6tqtrNPEic8A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_vr3LQYU-Ee6tqtrNPEic8A"/>
        <condition xmi:type="expression:Expression" xmi:id="_vr3LQoU-Ee6tqtrNPEic8A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_4NvgEIbbEe6NpJx4hoX1Ww" target="_1KyFYIbbEe6NpJx4hoX1Ww" source="_KHuGYIU8Ee60zYC5i_hnmg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_4NvgEYbbEe6NpJx4hoX1Ww"/>
        <condition xmi:type="expression:Expression" xmi:id="_4NvgEobbEe6NpJx4hoX1Ww" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_4o05kIbbEe6NpJx4hoX1Ww" target="_PouQ0IU8Ee60zYC5i_hnmg" source="_1KyFYIbbEe6NpJx4hoX1Ww">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_4o05kYbbEe6NpJx4hoX1Ww"/>
        <condition xmi:type="expression:Expression" xmi:id="_4o05kobbEe6NpJx4hoX1Ww" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_cjh6YIU8Ee60zYC5i_hnmg" name="Application" initiator="true"/>
      <parameters xmi:type="parameter:Parameter" xmi:id="_lrIEIIVUEe6tqtrNPEic8A" name="baseUrl_dukcapil" typeClassname="java.lang.String"/>
      <parameters xmi:type="parameter:Parameter" xmi:id="_oEu_0IVUEe6tqtrNPEic8A" name="baseUrl_peduli_lindungi" typeClassname="java.lang.String"/>
      <parameters xmi:type="parameter:Parameter" xmi:id="_q1oaIIVUEe6tqtrNPEic8A" name="baseUrl_wrapper" typeClassname="java.lang.String"/>
      <contract xmi:type="process:Contract" xmi:id="_0Zm0O4U7Ee60zYC5i_hnmg">
        <inputs xmi:type="process:ContractInput" xmi:id="_99NKAIbrEe6NpJx4hoX1Ww" name="id_number">
          <mapping xmi:type="process:ContractInputMapping" xmi:id="_99NKAYbrEe6NpJx4hoX1Ww"/>
        </inputs>
      </contract>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_0Zm0PIU7Ee60zYC5i_hnmg">
        <name xmi:type="expression:Expression" xmi:id="_0Zm0PYU7Ee60zYC5i_hnmg" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_0Zm0PoU7Ee60zYC5i_hnmg" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_0Zm0P4U7Ee60zYC5i_hnmg">
        <name xmi:type="expression:Expression" xmi:id="_0Zm0QIU7Ee60zYC5i_hnmg" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_0Zm0QYU7Ee60zYC5i_hnmg" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_0Zm0QoU7Ee60zYC5i_hnmg">
        <name xmi:type="expression:Expression" xmi:id="_0Zm0Q4U7Ee60zYC5i_hnmg" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_0Zm0RIU7Ee60zYC5i_hnmg" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_0Zm0RYU7Ee60zYC5i_hnmg">
        <name xmi:type="expression:Expression" xmi:id="_0Zm0RoU7Ee60zYC5i_hnmg" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_0Zm0R4U7Ee60zYC5i_hnmg" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_0Zm0SIU7Ee60zYC5i_hnmg">
        <name xmi:type="expression:Expression" xmi:id="_0Zm0SYU7Ee60zYC5i_hnmg" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_0Zm0SoU7Ee60zYC5i_hnmg" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <elements xmi:type="process:Pool" xmi:id="_HAjhIIU8Ee60zYC5i_hnmg" name="booking_flow">
      <elements xmi:type="process:Lane" xmi:id="_7-WeUIVDEe6tqtrNPEic8A" name="Application" actor="_3M_oIIVDEe6tqtrNPEic8A">
        <elements xmi:type="process:StartEvent" xmi:id="_2ZBcQIU9Ee6tqtrNPEic8A" name="Start Booking" outgoing="_AeaicIU_Ee6tqtrNPEic8A">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_2ZEfkYU9Ee6tqtrNPEic8A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_2ZEfkIU9Ee6tqtrNPEic8A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_2ZEfkoU9Ee6tqtrNPEic8A" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_4N0lQIU-Ee6tqtrNPEic8A" name="Send Email Invoice" outgoing="_Jar54IU_Ee6tqtrNPEic8A" incoming="_AeaicIU_Ee6tqtrNPEic8A">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_4N0lQYU-Ee6tqtrNPEic8A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_4N0lQoU-Ee6tqtrNPEic8A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_4N0lQ4U-Ee6tqtrNPEic8A" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_4N0lRIU-Ee6tqtrNPEic8A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_4N0lRYU-Ee6tqtrNPEic8A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_4N0lRoU-Ee6tqtrNPEic8A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_4N0lR4U-Ee6tqtrNPEic8A" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_4N0lSIU-Ee6tqtrNPEic8A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_B0ztoIU_Ee6tqtrNPEic8A" name="Send email payment receipt" outgoing="_Q7pJ4IU_Ee6tqtrNPEic8A" incoming="_JxhFgIU_Ee6tqtrNPEic8A">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_B0ztoYU_Ee6tqtrNPEic8A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_B0ztooU_Ee6tqtrNPEic8A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_B0zto4U_Ee6tqtrNPEic8A" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_B0ztpIU_Ee6tqtrNPEic8A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_B0ztpYU_Ee6tqtrNPEic8A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_B0ztpoU_Ee6tqtrNPEic8A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_B00UsIU_Ee6tqtrNPEic8A" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_B00UsYU_Ee6tqtrNPEic8A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_a96gEIU_Ee6tqtrNPEic8A" name="Validate Covid Status" outgoing="_i4UK0IU_Ee6tqtrNPEic8A" incoming="_dDRqEIU_Ee6tqtrNPEic8A">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_a97HIYU_Ee6tqtrNPEic8A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_a97HIIU_Ee6tqtrNPEic8A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_a97HIoU_Ee6tqtrNPEic8A" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_a97HI4U_Ee6tqtrNPEic8A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_a97HJIU_Ee6tqtrNPEic8A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_a97HJYU_Ee6tqtrNPEic8A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_a97HJ4U_Ee6tqtrNPEic8A" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_a97HJoU_Ee6tqtrNPEic8A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_iifr0IU_Ee6tqtrNPEic8A" name="Decision Flight" outgoing="_qjlNYIU_Ee6tqtrNPEic8A _21uUcIU_Ee6tqtrNPEic8A" incoming="_i4UK0IU_Ee6tqtrNPEic8A">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_iigS4YU_Ee6tqtrNPEic8A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_iigS4IU_Ee6tqtrNPEic8A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_iigS4oU_Ee6tqtrNPEic8A" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_pApbAIU_Ee6tqtrNPEic8A" name="Send Email Notification Not Eligible Flight" outgoing="_y5d9cIVDEe6tqtrNPEic8A" incoming="_qjlNYIU_Ee6tqtrNPEic8A">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_pApbAoU_Ee6tqtrNPEic8A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_pApbAYU_Ee6tqtrNPEic8A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_pApbA4U_Ee6tqtrNPEic8A" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_pApbBIU_Ee6tqtrNPEic8A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_pApbBYU_Ee6tqtrNPEic8A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_pApbBoU_Ee6tqtrNPEic8A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_pApbCIU_Ee6tqtrNPEic8A" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_pApbB4U_Ee6tqtrNPEic8A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_wgFoEIU_Ee6tqtrNPEic8A" name="Send Email Notification Boarding Ticket" outgoing="_zSLYYIVDEe6tqtrNPEic8A" incoming="_21uUcIU_Ee6tqtrNPEic8A">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_wgFoEYU_Ee6tqtrNPEic8A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_wgFoEoU_Ee6tqtrNPEic8A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_wgFoE4U_Ee6tqtrNPEic8A" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_wgFoFIU_Ee6tqtrNPEic8A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_wgFoFYU_Ee6tqtrNPEic8A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_wgFoFoU_Ee6tqtrNPEic8A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_wgFoF4U_Ee6tqtrNPEic8A" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_wgFoGIU_Ee6tqtrNPEic8A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndTerminatedEvent" xmi:id="_xoqc4IVDEe6tqtrNPEic8A" name="End" incoming="_y5d9cIVDEe6tqtrNPEic8A _zSLYYIVDEe6tqtrNPEic8A">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_xorD8YVDEe6tqtrNPEic8A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_xorD8IVDEe6tqtrNPEic8A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_xorD8oVDEe6tqtrNPEic8A" name="" content="" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_CkJtoIVEEe6tqtrNPEic8A" name="User" actor="_EqcrwIVEEe6tqtrNPEic8A">
        <elements xmi:type="process:Task" xmi:id="_HqjZAIU_Ee6tqtrNPEic8A" name="Do Payment" outgoing="_JxhFgIU_Ee6tqtrNPEic8A" incoming="_Jar54IU_Ee6tqtrNPEic8A" actor="_EqcrwIVEEe6tqtrNPEic8A" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_HqkAEYU_Ee6tqtrNPEic8A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_HqkAEIU_Ee6tqtrNPEic8A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_HqkAEoU_Ee6tqtrNPEic8A" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_HqkAE4U_Ee6tqtrNPEic8A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_HqkAFIU_Ee6tqtrNPEic8A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_HqkAFYU_Ee6tqtrNPEic8A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_HqkAF4U_Ee6tqtrNPEic8A" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_HqkAFoU_Ee6tqtrNPEic8A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_HqkAGYU_Ee6tqtrNPEic8A" type="NONE">
            <targetForm xmi:type="expression:Expression" xmi:id="_UlBmMIVREe6tqtrNPEic8A" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_HqkAGIU_Ee6tqtrNPEic8A"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_HqkAG4U_Ee6tqtrNPEic8A" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_PiHLIIU_Ee6tqtrNPEic8A" name="Redeem Ticket" outgoing="_dDRqEIU_Ee6tqtrNPEic8A" incoming="_Q7pJ4IU_Ee6tqtrNPEic8A" actor="_EqcrwIVEEe6tqtrNPEic8A" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_PiHLIoU_Ee6tqtrNPEic8A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_PiHLIYU_Ee6tqtrNPEic8A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_PiHLI4U_Ee6tqtrNPEic8A" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_PiHLJIU_Ee6tqtrNPEic8A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_PiHLJYU_Ee6tqtrNPEic8A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_PiHLJoU_Ee6tqtrNPEic8A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_PiHLKIU_Ee6tqtrNPEic8A" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_PiHLJ4U_Ee6tqtrNPEic8A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_PiHLKoU_Ee6tqtrNPEic8A" type="NONE">
            <targetForm xmi:type="expression:Expression" xmi:id="_UlBmMYVREe6tqtrNPEic8A" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_PiHLKYU_Ee6tqtrNPEic8A"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_PiHLLIU_Ee6tqtrNPEic8A" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
      </elements>
      <formMapping xmi:type="process:FormMapping" xmi:id="_HAkIP4U8Ee60zYC5i_hnmg" type="NONE">
        <targetForm xmi:type="expression:Expression" xmi:id="_QW0gYoVREe6tqtrNPEic8A" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_HAkIQYU8Ee60zYC5i_hnmg" type="NONE">
        <targetForm xmi:type="expression:Expression" xmi:id="_HAkIQoU8Ee60zYC5i_hnmg" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_AeaicIU_Ee6tqtrNPEic8A" target="_4N0lQIU-Ee6tqtrNPEic8A" source="_2ZBcQIU9Ee6tqtrNPEic8A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_AebJgIU_Ee6tqtrNPEic8A"/>
        <condition xmi:type="expression:Expression" xmi:id="_AebJgYU_Ee6tqtrNPEic8A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Jar54IU_Ee6tqtrNPEic8A" target="_HqjZAIU_Ee6tqtrNPEic8A" source="_4N0lQIU-Ee6tqtrNPEic8A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Jar54YU_Ee6tqtrNPEic8A"/>
        <condition xmi:type="expression:Expression" xmi:id="_Jar54oU_Ee6tqtrNPEic8A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_JxhFgIU_Ee6tqtrNPEic8A" target="_B0ztoIU_Ee6tqtrNPEic8A" source="_HqjZAIU_Ee6tqtrNPEic8A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_JxhFgYU_Ee6tqtrNPEic8A"/>
        <condition xmi:type="expression:Expression" xmi:id="_JxhFgoU_Ee6tqtrNPEic8A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Q7pJ4IU_Ee6tqtrNPEic8A" target="_PiHLIIU_Ee6tqtrNPEic8A" source="_B0ztoIU_Ee6tqtrNPEic8A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Q7pJ4YU_Ee6tqtrNPEic8A"/>
        <condition xmi:type="expression:Expression" xmi:id="_Q7pJ4oU_Ee6tqtrNPEic8A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_dDRqEIU_Ee6tqtrNPEic8A" target="_a96gEIU_Ee6tqtrNPEic8A" source="_PiHLIIU_Ee6tqtrNPEic8A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_dDSRIIU_Ee6tqtrNPEic8A"/>
        <condition xmi:type="expression:Expression" xmi:id="_dDSRIYU_Ee6tqtrNPEic8A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_i4UK0IU_Ee6tqtrNPEic8A" target="_iifr0IU_Ee6tqtrNPEic8A" source="_a96gEIU_Ee6tqtrNPEic8A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_i4UK0YU_Ee6tqtrNPEic8A"/>
        <condition xmi:type="expression:Expression" xmi:id="_i4UK0oU_Ee6tqtrNPEic8A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_qjlNYIU_Ee6tqtrNPEic8A" name="No" target="_pApbAIU_Ee6tqtrNPEic8A" source="_iifr0IU_Ee6tqtrNPEic8A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_qjlNYYU_Ee6tqtrNPEic8A"/>
        <condition xmi:type="expression:Expression" xmi:id="_qjlNYoU_Ee6tqtrNPEic8A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_21uUcIU_Ee6tqtrNPEic8A" name="Yes" target="_wgFoEIU_Ee6tqtrNPEic8A" source="_iifr0IU_Ee6tqtrNPEic8A" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_21uUcYU_Ee6tqtrNPEic8A"/>
        <condition xmi:type="expression:Expression" xmi:id="_21uUcoU_Ee6tqtrNPEic8A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_y5d9cIVDEe6tqtrNPEic8A" target="_xoqc4IVDEe6tqtrNPEic8A" source="_pApbAIU_Ee6tqtrNPEic8A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_y5d9cYVDEe6tqtrNPEic8A"/>
        <condition xmi:type="expression:Expression" xmi:id="_y5d9coVDEe6tqtrNPEic8A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_zSLYYIVDEe6tqtrNPEic8A" target="_xoqc4IVDEe6tqtrNPEic8A" source="_wgFoEIU_Ee6tqtrNPEic8A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_zSLYYYVDEe6tqtrNPEic8A"/>
        <condition xmi:type="expression:Expression" xmi:id="_zSLYYoVDEe6tqtrNPEic8A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_3M_oIIVDEe6tqtrNPEic8A" name="Application" initiator="true"/>
      <actors xmi:type="process:Actor" xmi:id="_EqcrwIVEEe6tqtrNPEic8A" name="User"/>
      <contract xmi:type="process:Contract" xmi:id="_HAkIQ4U8Ee60zYC5i_hnmg"/>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_HAkIMIU8Ee60zYC5i_hnmg">
        <name xmi:type="expression:Expression" xmi:id="_HAkIMYU8Ee60zYC5i_hnmg" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_HAkIMoU8Ee60zYC5i_hnmg" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_HAkIM4U8Ee60zYC5i_hnmg">
        <name xmi:type="expression:Expression" xmi:id="_HAkINIU8Ee60zYC5i_hnmg" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_HAkINYU8Ee60zYC5i_hnmg" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_HAkINoU8Ee60zYC5i_hnmg">
        <name xmi:type="expression:Expression" xmi:id="_HAkIN4U8Ee60zYC5i_hnmg" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_HAkIOIU8Ee60zYC5i_hnmg" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_HAkIOYU8Ee60zYC5i_hnmg">
        <name xmi:type="expression:Expression" xmi:id="_HAkIOoU8Ee60zYC5i_hnmg" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_HAkIO4U8Ee60zYC5i_hnmg" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_HAkIPIU8Ee60zYC5i_hnmg">
        <name xmi:type="expression:Expression" xmi:id="_HAkIPYU8Ee60zYC5i_hnmg" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_HAkIPoU8Ee60zYC5i_hnmg" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <datatypes xmi:type="process:BooleanType" xmi:id="_0Zm0S4U7Ee60zYC5i_hnmg" name="Boolean"/>
    <datatypes xmi:type="process:DateType" xmi:id="_0Zm0TIU7Ee60zYC5i_hnmg" name="Date"/>
    <datatypes xmi:type="process:IntegerType" xmi:id="_0Zm0TYU7Ee60zYC5i_hnmg" name="Integer"/>
    <datatypes xmi:type="process:LongType" xmi:id="_0Zm0ToU7Ee60zYC5i_hnmg" name="Long"/>
    <datatypes xmi:type="process:DoubleType" xmi:id="_0Zm0T4U7Ee60zYC5i_hnmg" name="Double"/>
    <datatypes xmi:type="process:StringType" xmi:id="_0Zm0UIU7Ee60zYC5i_hnmg" name="Text"/>
    <datatypes xmi:type="process:JavaType" xmi:id="_0Zm0UYU7Ee60zYC5i_hnmg" name="Java_object"/>
    <datatypes xmi:type="process:XMLType" xmi:id="_0Zm0UoU7Ee60zYC5i_hnmg" name="XML"/>
    <datatypes xmi:type="process:BusinessObjectType" xmi:id="_0Zm0U4U7Ee60zYC5i_hnmg" name="Business_Object"/>
  </process:MainProcess>
  <notation:Diagram xmi:id="_0Zm0VIU7Ee60zYC5i_hnmg" type="Process" element="_0ZmNEIU7Ee60zYC5i_hnmg" name="MyDiagram" measurementUnit="Pixel">
    <children xmi:type="notation:Node" xmi:id="_0Zm0VYU7Ee60zYC5i_hnmg" type="2007" element="_0Zm0IIU7Ee60zYC5i_hnmg">
      <children xmi:type="notation:DecorationNode" xmi:id="_0Zm0VoU7Ee60zYC5i_hnmg" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_0Zm0V4U7Ee60zYC5i_hnmg" type="7001">
        <children xmi:type="notation:Node" xmi:id="_0Zm0WIU7Ee60zYC5i_hnmg" type="3007" element="_0Zm0IYU7Ee60zYC5i_hnmg">
          <children xmi:type="notation:DecorationNode" xmi:id="_0Zm0WYU7Ee60zYC5i_hnmg" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_0Zm0WoU7Ee60zYC5i_hnmg" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_0Zm0XoU7Ee60zYC5i_hnmg" type="3002" element="_0Zm0IoU7Ee60zYC5i_hnmg" fontName=".AppleSystemUIFont">
              <children xmi:type="notation:DecorationNode" xmi:id="_0Zm0X4U7Ee60zYC5i_hnmg" type="5024">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_0Zm0YIU7Ee60zYC5i_hnmg" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_0Zm0YYU7Ee60zYC5i_hnmg" x="60" y="68"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_-yprkIU7Ee60zYC5i_hnmg" type="3027" element="_-yn2YIU7Ee60zYC5i_hnmg" fontName=".AppleSystemUIFont" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_-yprkoU7Ee60zYC5i_hnmg" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_-yprkYU7Ee60zYC5i_hnmg" x="511" y="53" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_KHutcIU8Ee60zYC5i_hnmg" type="3027" element="_KHuGYIU8Ee60zYC5i_hnmg" fontName=".AppleSystemUIFont" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_KHutcoU8Ee60zYC5i_hnmg" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_KHutcYU8Ee60zYC5i_hnmg" x="694" y="53" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Pove8IU8Ee60zYC5i_hnmg" type="3062" element="_PouQ0IU8Ee60zYC5i_hnmg" fontName=".AppleSystemUIFont">
              <children xmi:type="notation:DecorationNode" xmi:id="_Pove8oU8Ee60zYC5i_hnmg" type="5090">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_Pove84U8Ee60zYC5i_hnmg" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Pove8YU8Ee60zYC5i_hnmg" x="1015" y="68"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_UJuE5IU-Ee6tqtrNPEic8A" type="3027" element="_UJtd0IU-Ee6tqtrNPEic8A" fontName=".AppleSystemUIFont" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_UJuE5YU-Ee6tqtrNPEic8A" type="5017" element="_UJtd0IU-Ee6tqtrNPEic8A"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_UJuE5oU-Ee6tqtrNPEic8A" x="160" y="53" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_rLUYQYU-Ee6tqtrNPEic8A" type="3027" element="_rLTxMIU-Ee6tqtrNPEic8A" fontName=".AppleSystemUIFont" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_rLUYQoU-Ee6tqtrNPEic8A" type="5017" element="_rLTxMIU-Ee6tqtrNPEic8A"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_rLUYQ4U-Ee6tqtrNPEic8A" x="329" y="53" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_1LMVEIbbEe6NpJx4hoX1Ww" type="3027" element="_1KyFYIbbEe6NpJx4hoX1Ww" fontName=".AppleSystemUIFont" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_1LM8IIbbEe6NpJx4hoX1Ww" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_1LMVEYbbEe6NpJx4hoX1Ww" x="859" y="58"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_0Zm0YoU7Ee60zYC5i_hnmg"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_0Zm0Y4U7Ee60zYC5i_hnmg" fontName=".AppleSystemUIFont"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_0Zm0ZIU7Ee60zYC5i_hnmg"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_0Zm0ZYU7Ee60zYC5i_hnmg"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_0Zm0ZoU7Ee60zYC5i_hnmg" x="44" y="10" width="1301" height="181"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_0Zm0Z4U7Ee60zYC5i_hnmg"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_0Zm0aIU7Ee60zYC5i_hnmg" fontName=".AppleSystemUIFont"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_0Zm0aYU7Ee60zYC5i_hnmg"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_0Zm0aoU7Ee60zYC5i_hnmg"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_0Zm0a4U7Ee60zYC5i_hnmg" width="1320" height="334"/>
    </children>
    <children xmi:type="notation:Node" xmi:id="_HAkvQIU8Ee60zYC5i_hnmg" type="2007" element="_HAjhIIU8Ee60zYC5i_hnmg">
      <children xmi:type="notation:DecorationNode" xmi:id="_HAlWUIU8Ee60zYC5i_hnmg" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_HAlWUYU8Ee60zYC5i_hnmg" type="7001">
        <children xmi:type="notation:Node" xmi:id="_7-XFYIVDEe6tqtrNPEic8A" type="3007" element="_7-WeUIVDEe6tqtrNPEic8A">
          <children xmi:type="notation:DecorationNode" xmi:id="_7-XscIVDEe6tqtrNPEic8A" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_7-XscYVDEe6tqtrNPEic8A" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_2ZFtsIU9Ee6tqtrNPEic8A" type="3002" element="_2ZBcQIU9Ee6tqtrNPEic8A" fontName=".AppleSystemUIFont">
              <children xmi:type="notation:DecorationNode" xmi:id="_2ZFtsoU9Ee6tqtrNPEic8A" type="5024">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_2ZFts4U9Ee6tqtrNPEic8A" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_2ZFtsYU9Ee6tqtrNPEic8A" x="54" y="130"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_4N0lSYU-Ee6tqtrNPEic8A" type="3027" element="_4N0lQIU-Ee6tqtrNPEic8A" fontName=".AppleSystemUIFont" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_4N0lSoU-Ee6tqtrNPEic8A" type="5017" element="_4N0lQIU-Ee6tqtrNPEic8A"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_4N1MUIU-Ee6tqtrNPEic8A" x="162" y="115" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_B00UsoU_Ee6tqtrNPEic8A" type="3027" element="_B0ztoIU_Ee6tqtrNPEic8A" fontName=".AppleSystemUIFont" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_B00Us4U_Ee6tqtrNPEic8A" type="5017" element="_B0ztoIU_Ee6tqtrNPEic8A"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_B00UtIU_Ee6tqtrNPEic8A" x="343" y="115" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_a97HKIU_Ee6tqtrNPEic8A" type="3027" element="_a96gEIU_Ee6tqtrNPEic8A" fontName=".AppleSystemUIFont" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_a97uMIU_Ee6tqtrNPEic8A" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_a97HKYU_Ee6tqtrNPEic8A" x="539" y="115" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_iig58IU_Ee6tqtrNPEic8A" type="3008" element="_iifr0IU_Ee6tqtrNPEic8A" fontName=".AppleSystemUIFont">
              <children xmi:type="notation:DecorationNode" xmi:id="_iig58oU_Ee6tqtrNPEic8A" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_iig584U_Ee6tqtrNPEic8A" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_iig58YU_Ee6tqtrNPEic8A" x="707" y="123"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_pAqCEIU_Ee6tqtrNPEic8A" type="3027" element="_pApbAIU_Ee6tqtrNPEic8A" fontName=".AppleSystemUIFont" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_pAqCEoU_Ee6tqtrNPEic8A" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_pAqCEYU_Ee6tqtrNPEic8A" x="819" y="123" width="140" height="70"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_wgFoGYU_Ee6tqtrNPEic8A" type="3027" element="_wgFoEIU_Ee6tqtrNPEic8A" fontName=".AppleSystemUIFont" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_wgFoGoU_Ee6tqtrNPEic8A" type="5017" element="_wgFoEIU_Ee6tqtrNPEic8A"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_wgFoG4U_Ee6tqtrNPEic8A" x="819" y="221" width="140" height="70"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_xosSEIVDEe6tqtrNPEic8A" type="3062" element="_xoqc4IVDEe6tqtrNPEic8A" fontName=".AppleSystemUIFont">
              <children xmi:type="notation:DecorationNode" xmi:id="_xos5IYVDEe6tqtrNPEic8A" type="5090">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_xos5IoVDEe6tqtrNPEic8A" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_xos5IIVDEe6tqtrNPEic8A" x="1057" y="192"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_7-XFYYVDEe6tqtrNPEic8A"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_7-XFYoVDEe6tqtrNPEic8A" fontName=".AppleSystemUIFont"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_7-XFY4VDEe6tqtrNPEic8A"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_7-XscoVDEe6tqtrNPEic8A"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_7-XFZIVDEe6tqtrNPEic8A" x="44" y="10" width="1301" height="314"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_CkKUsIVEEe6tqtrNPEic8A" type="3007" element="_CkJtoIVEEe6tqtrNPEic8A">
          <children xmi:type="notation:DecorationNode" xmi:id="_CkKUtYVEEe6tqtrNPEic8A" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_CkKUtoVEEe6tqtrNPEic8A" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_HqrU0IU_Ee6tqtrNPEic8A" type="3005" element="_HqjZAIU_Ee6tqtrNPEic8A" fontName=".AppleSystemUIFont" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_HqrU0oU_Ee6tqtrNPEic8A" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_HqrU0YU_Ee6tqtrNPEic8A" x="172" y="71"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_PiHyMIU_Ee6tqtrNPEic8A" type="3005" element="_PiHLIIU_Ee6tqtrNPEic8A" fontName=".AppleSystemUIFont" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_PiHyMoU_Ee6tqtrNPEic8A" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_PiHyMYU_Ee6tqtrNPEic8A" x="355" y="71"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_CkKUsYVEEe6tqtrNPEic8A"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_CkKUsoVEEe6tqtrNPEic8A" fontName=".AppleSystemUIFont"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_CkKUs4VEEe6tqtrNPEic8A"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_CkKUt4VEEe6tqtrNPEic8A"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_CkKUtIVEEe6tqtrNPEic8A" x="44" y="314" width="1301" height="164"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_HAkvQYU8Ee60zYC5i_hnmg"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_HAkvQoU8Ee60zYC5i_hnmg" fontName=".AppleSystemUIFont"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_HAkvQ4U8Ee60zYC5i_hnmg"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_HAlWUoU8Ee60zYC5i_hnmg"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_HAkvRIU8Ee60zYC5i_hnmg" width="1320" height="464"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_0Zm0bIU7Ee60zYC5i_hnmg"/>
    <edges xmi:type="notation:Connector" xmi:id="_0Zm0bYU7Ee60zYC5i_hnmg" type="4001" element="_0Zm0N4U7Ee60zYC5i_hnmg" source="_0Zm0XoU7Ee60zYC5i_hnmg" target="_UJuE5IU-Ee6tqtrNPEic8A" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_0Zm0boU7Ee60zYC5i_hnmg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_0Zm0b4U7Ee60zYC5i_hnmg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_0Zm0cIU7Ee60zYC5i_hnmg" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_0Zm0cYU7Ee60zYC5i_hnmg" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_omIesIU-Ee6tqtrNPEic8A" id="(0.016666666666666666,0.43333333333333335)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_OBGywIU8Ee60zYC5i_hnmg" type="4001" element="_OBGLsIU8Ee60zYC5i_hnmg" source="_-yprkIU7Ee60zYC5i_hnmg" target="_KHutcIU8Ee60zYC5i_hnmg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_OBHZ0IU8Ee60zYC5i_hnmg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_OBHZ0YU8Ee60zYC5i_hnmg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_OBGywYU8Ee60zYC5i_hnmg" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_OBGywoU8Ee60zYC5i_hnmg" points="[0, 3, -64, 7]$[63, 3, -1, 7]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_OBIn8IU8Ee60zYC5i_hnmg" id="(1.0,0.43333333333333335)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_OBIn8YU8Ee60zYC5i_hnmg" id="(0.008333333333333333,0.36666666666666664)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_tkfPEIU-Ee6tqtrNPEic8A" type="4001" element="_tkeA8IU-Ee6tqtrNPEic8A" source="_UJuE5IU-Ee6tqtrNPEic8A" target="_rLUYQYU-Ee6tqtrNPEic8A" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_tkfPE4U-Ee6tqtrNPEic8A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_tkfPFIU-Ee6tqtrNPEic8A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_tkfPEYU-Ee6tqtrNPEic8A" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_tkfPEoU-Ee6tqtrNPEic8A" points="[0, -2, -52, 0]$[49, -3, -3, -1]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_tkhEQIU-Ee6tqtrNPEic8A" id="(1.0,0.48333333333333334)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_tkhEQYU-Ee6tqtrNPEic8A" id="(0.025,0.45)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_vr3yUIU-Ee6tqtrNPEic8A" type="4001" element="_vr3LQIU-Ee6tqtrNPEic8A" source="_rLUYQYU-Ee6tqtrNPEic8A" target="_-yprkIU7Ee60zYC5i_hnmg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_vr3yU4U-Ee6tqtrNPEic8A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_vr4ZYIU-Ee6tqtrNPEic8A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_vr3yUYU-Ee6tqtrNPEic8A" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_vr3yUoU-Ee6tqtrNPEic8A" points="[-99, -26, 137, 36]$[-238, -58, -2, 4]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_vr5ngIU-Ee6tqtrNPEic8A" id="(1.0,0.43333333333333335)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_vr5ngYU-Ee6tqtrNPEic8A" id="(0.0,0.45)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_AebJgoU_Ee6tqtrNPEic8A" type="4001" element="_AeaicIU_Ee6tqtrNPEic8A" source="_2ZFtsIU9Ee6tqtrNPEic8A" target="_4N0lSYU-Ee6tqtrNPEic8A" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_AebwkIU_Ee6tqtrNPEic8A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_AebwkYU_Ee6tqtrNPEic8A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_AebJg4U_Ee6tqtrNPEic8A" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_AebJhIU_Ee6tqtrNPEic8A" points="[-8, 1, -80, 13]$[68, -13, -4, -1]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_Aec-sIU_Ee6tqtrNPEic8A" id="(1.0,0.8666666666666667)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_Aec-sYU_Ee6tqtrNPEic8A" id="(0.03333333333333333,0.48333333333333334)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_Jasg8IU_Ee6tqtrNPEic8A" type="4001" element="_Jar54IU_Ee6tqtrNPEic8A" source="_4N0lSYU-Ee6tqtrNPEic8A" target="_HqrU0IU_Ee6tqtrNPEic8A" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_Jasg84U_Ee6tqtrNPEic8A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_Jasg9IU_Ee6tqtrNPEic8A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_Jasg8YU_Ee6tqtrNPEic8A" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_Jasg8oU_Ee6tqtrNPEic8A" points="[-4, 1, -12, -440]$[-4, 439, -12, -2]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_JatvEIU_Ee6tqtrNPEic8A" id="(0.49166666666666664,0.9833333333333333)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_JatvEYU_Ee6tqtrNPEic8A" id="(0.59,0.04)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_JxhskIU_Ee6tqtrNPEic8A" type="4001" element="_JxhFgIU_Ee6tqtrNPEic8A" source="_HqrU0IU_Ee6tqtrNPEic8A" target="_B00UsoU_Ee6tqtrNPEic8A" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_Jxhsk4U_Ee6tqtrNPEic8A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_JxhslIU_Ee6tqtrNPEic8A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_JxhskYU_Ee6tqtrNPEic8A" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_JxhskoU_Ee6tqtrNPEic8A" points="[0, -2, -72, 0]$[68, -2, -4, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_Jxi6sIU_Ee6tqtrNPEic8A" id="(1.0,0.62)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_Jxi6sYU_Ee6tqtrNPEic8A" id="(0.016666666666666666,0.4166666666666667)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_Q7pw8IU_Ee6tqtrNPEic8A" type="4001" element="_Q7pJ4IU_Ee6tqtrNPEic8A" source="_B00UsoU_Ee6tqtrNPEic8A" target="_PiHyMIU_Ee6tqtrNPEic8A" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_Q7pw84U_Ee6tqtrNPEic8A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_Q7pw9IU_Ee6tqtrNPEic8A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_Q7pw8YU_Ee6tqtrNPEic8A" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_Q7pw8oU_Ee6tqtrNPEic8A" points="[0, -3, -76, 0]$[76, -3, 0, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_Q7q_EIU_Ee6tqtrNPEic8A" id="(0.4666666666666667,0.95)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_Q7q_EYU_Ee6tqtrNPEic8A" id="(0.5,0.1)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_dDSRIoU_Ee6tqtrNPEic8A" type="4001" element="_dDRqEIU_Ee6tqtrNPEic8A" source="_PiHyMIU_Ee6tqtrNPEic8A" target="_a97HKIU_Ee6tqtrNPEic8A" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_dDS4MIU_Ee6tqtrNPEic8A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_dDS4MYU_Ee6tqtrNPEic8A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_dDSRI4U_Ee6tqtrNPEic8A" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_dDSRJIU_Ee6tqtrNPEic8A" points="[0, 1, -69, 0]$[68, 0, -1, -1]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_dDTfQIU_Ee6tqtrNPEic8A" id="(1.0,0.52)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_dDTfQYU_Ee6tqtrNPEic8A" id="(0.008333333333333333,0.45)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_i4Ux4IU_Ee6tqtrNPEic8A" type="4001" element="_i4UK0IU_Ee6tqtrNPEic8A" source="_a97HKIU_Ee6tqtrNPEic8A" target="_iig58IU_Ee6tqtrNPEic8A" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_i4Ux44U_Ee6tqtrNPEic8A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_i4Ux5IU_Ee6tqtrNPEic8A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_i4Ux4YU_Ee6tqtrNPEic8A" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_i4Ux4oU_Ee6tqtrNPEic8A" points="[0, 1, 0, 0]$[0, 1, 0, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_i4WAAIU_Ee6tqtrNPEic8A" id="(1.0,0.45)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_i4WAAYU_Ee6tqtrNPEic8A" id="(0.16279069767441862,0.46511627906976744)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_qjnCkIU_Ee6tqtrNPEic8A" type="4001" element="_qjlNYIU_Ee6tqtrNPEic8A" source="_iig58IU_Ee6tqtrNPEic8A" target="_pAqCEIU_Ee6tqtrNPEic8A" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_qjnCk4U_Ee6tqtrNPEic8A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_qjnClIU_Ee6tqtrNPEic8A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_qjnCkYU_Ee6tqtrNPEic8A" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_qjnCkoU_Ee6tqtrNPEic8A" points="[0, -4, -69, -8]$[69, -4, 0, -8]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_qjoQsIU_Ee6tqtrNPEic8A" id="(1.0,0.5813953488372093)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_qjoQsYU_Ee6tqtrNPEic8A" id="(0.0,0.42)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_2123UIU_Ee6tqtrNPEic8A" type="4001" element="_21uUcIU_Ee6tqtrNPEic8A" source="_iig58IU_Ee6tqtrNPEic8A" target="_wgFoGYU_Ee6tqtrNPEic8A" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_2123U4U_Ee6tqtrNPEic8A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_2123VIU_Ee6tqtrNPEic8A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_2123UYU_Ee6tqtrNPEic8A" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_2123UoU_Ee6tqtrNPEic8A" points="[-5, -7, -74, -105]$[69, 98, 0, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_213eYIU_Ee6tqtrNPEic8A" id="(0.4186046511627907,0.9069767441860465)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_213eYYU_Ee6tqtrNPEic8A" id="(0.0,0.45714285714285713)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_y5ekgIVDEe6tqtrNPEic8A" type="4001" element="_y5d9cIVDEe6tqtrNPEic8A" source="_pAqCEIU_Ee6tqtrNPEic8A" target="_xosSEIVDEe6tqtrNPEic8A" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_y5ekg4VDEe6tqtrNPEic8A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_y5ekhIVDEe6tqtrNPEic8A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_y5ekgYVDEe6tqtrNPEic8A" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_y5ekgoVDEe6tqtrNPEic8A" points="[0, 0, -56, -42]$[56, 0, 0, -42]$[56, 39, 0, -3]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_y5fyoIVDEe6tqtrNPEic8A" id="(1.0,0.42857142857142855)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_y5fyoYVDEe6tqtrNPEic8A" id="(0.4666666666666667,0.1)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_zSL_cIVDEe6tqtrNPEic8A" type="4001" element="_zSLYYIVDEe6tqtrNPEic8A" source="_wgFoGYU_Ee6tqtrNPEic8A" target="_xosSEIVDEe6tqtrNPEic8A" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_zSL_c4VDEe6tqtrNPEic8A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_zSL_dIVDEe6tqtrNPEic8A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_zSL_cYVDEe6tqtrNPEic8A" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_zSL_coVDEe6tqtrNPEic8A" points="[0, 0, -57, 45]$[56, -31, -1, 14]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_zSMmgIVDEe6tqtrNPEic8A" id="(1.0,0.44285714285714284)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_z0hQcIVDEe6tqtrNPEic8A" id="(0.5333333333333333,0.9333333333333333)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_4NwuMIbbEe6NpJx4hoX1Ww" type="4001" element="_4NvgEIbbEe6NpJx4hoX1Ww" source="_KHutcIU8Ee60zYC5i_hnmg" target="_1LMVEIbbEe6NpJx4hoX1Ww" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_4NwuM4bbEe6NpJx4hoX1Ww" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_4NwuNIbbEe6NpJx4hoX1Ww" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_4NwuMYbbEe6NpJx4hoX1Ww" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_4NwuMobbEe6NpJx4hoX1Ww" points="[0, -1, -47, 0]$[45, -1, -2, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_4NyjYIbbEe6NpJx4hoX1Ww" id="(1.0,0.5166666666666667)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_4NyjYYbbEe6NpJx4hoX1Ww" id="(0.02,0.5)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_4o1goIbbEe6NpJx4hoX1Ww" type="4001" element="_4o05kIbbEe6NpJx4hoX1Ww" source="_1LMVEIbbEe6NpJx4hoX1Ww" target="_Pove8IU8Ee60zYC5i_hnmg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_4o1go4bbEe6NpJx4hoX1Ww" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_4o1gpIbbEe6NpJx4hoX1Ww" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_4o1goYbbEe6NpJx4hoX1Ww" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_4o1goobbEe6NpJx4hoX1Ww" points="[0, -3, -60, 0]$[56, -3, -4, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_4o3V0IbbEe6NpJx4hoX1Ww" id="(1.0,0.58)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_4o3V0YbbEe6NpJx4hoX1Ww" id="(0.13333333333333333,0.5333333333333333)"/>
    </edges>
  </notation:Diagram>
</xmi:XMI>
